.github/workflows/merge-main.yml
.github/workflows/unit-tests.yml

Trivy is kicking up security alerts in main merge, which stops the pipeline.  Moving to the test/analysis workflow means running on ready PR, so stops can happen sooner and more visibly.
---
[Backend](https://nr-forest-client-105-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-105-frontend.apps.silver.devops.gov.bc.ca/) available

Moved Trivy to test/analysis workflow

---

.github/workflows/unit-tests.yml

SonarCloud has been set up in monorepo mode.  Test and Analyse Action only supports node at the moment, so the Java backend will have to wait a bit.
https://sonarcloud.io/project/overview?id=forest-client-backend
https://sonarcloud.io/project/overview?id=forest-client-frontend
---
[Backend](https://nr-forest-client-166-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-166-frontend.apps.silver.devops.gov.bc.ca/) available

Setup SonarCloud for Frontend using Action

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml

For predictability and stability use ubuntu-22.04 instead of ubuntu-latest in workflows.
---
[Backend](https://nr-forest-client-176-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-176-frontend.apps.silver.devops.gov.bc.ca/) available

Workflows use ubuntu-22.04 instead of ubuntu-latest

---

.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

Don't allow PR open and close workflows to run at the same time. This is confusing and can leave OpenShift artifacts behind.
Change:
- PR open and close use the same concurrency group name
- Newer runs cancel older runs
---
[Backend](https://nr-forest-client-250-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-250-frontend.apps.silver.devops.gov.bc.ca/) available

PR open and close cancel each other

---

.github/CODEOWNERS
backend/src/main/java/ca/bc/gov/app/configuration/RouteConfiguration.java
backend/src/main/java/ca/bc/gov/app/dto/orgbook/OrgBookNameDto.java
backend/src/main/java/ca/bc/gov/app/routes/client/ClientRouter.java
backend/src/main/java/ca/bc/gov/app/service/orgbook/OrgBookApiService.java
backend/src/test/java/ca/bc/gov/app/endpoints/client/ClientHandlerIntegrationTest.java

Changing endpoint names to plural
---
[Backend](https://nr-forest-client-337-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-337-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-337-legacy.apps.silver.devops.gov.bc.ca/) available

fix: fixing endpoint naming to plural

---

.github/dependabot.yml

Dial down Dependabot PR updates from daily to weekly, which defaults to Mondays.  Hopefully this should recude the burden of managing updates.  (Mend Renovate is still being worked  on to replace Dependabot, since it offers batching and other features.)
---
[Backend](https://nr-forest-client-361-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-361-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-361-legacy.apps.silver.devops.gov.bc.ca/) available

fix: reduce Dependabot frequency

---

.github/workflows/pr-open.yml

Change backend and legacy to matrix format on github action
---
[Backend](https://nr-forest-client-404-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-404-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-404-legacy.apps.silver.devops.gov.bc.ca/) available

Change backend and legacy to matrix format on github action

---

backend/src/main/java/ca/bc/gov/app/validator/client/ClientAddressDtoValidator.java

Change address validations so province and posta code are now mandatory
---
[Backend](https://nr-forest-client-451-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-451-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-451-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-760] Change address validations so province and posta code are now mandatory

---

.github/workflows/pr-open.yml

Only run PR comment adder on new or reopened PRs.  This prevents double-commenting (happens when GitHub responses time out) and avoids unnecessarily using a runner, which can be in short supply.
---
[Backend](https://nr-forest-client-485-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-485-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-485-legacy.apps.silver.devops.gov.bc.ca/) available

PR description add only for opened or reopened PRs

---

frontend/Caddyfile
frontend/Dockerfile
frontend/openshift.deploy.yml

Caddy update plus the OpenShift security context it requires.  The builder base was changed from RHEL's UBI to Alpine, which Caddy uses too.
Features: 
- LOG_LEVEL, which defaults to "info" and can be set in the template
- Common base for build and deploy, which is a little faster and more stable
- Lots of security updates, including warnings in this project
---
[Backend](https://nr-forest-client-505-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-505-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-505-legacy.apps.silver.devops.gov.bc.ca/) available …

feat: update caddy to 2.6.4

---

frontend/tests/unittests/composables/useFetch.spec.ts

---
[Backend](https://nr-forest-client-531-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-531-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-531-legacy.apps.silver.devops.gov.bc.ca/) available

fix(fe): Attempt to solve assertion error

---

backend/src/main/java/ca/bc/gov/app/dto/client/ClientTypeEnum.java
backend/src/main/java/ca/bc/gov/app/util/ClientMapper.java
backend/src/main/java/ca/bc/gov/app/util/ClientValidationUtils.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientAddressDtoValidator.java
backend/src/main/resources/db/migration/V1__initializing_data.sql
backend/src/main/resources/db/migration/V2__data_initialization.sql
backend/src/test/java/ca/bc/gov/app/service/client/ClientServiceIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/util/ClientValidationUtilsTest.java
frontend/.devcontainer/frontend.code-workspace
frontend/src/dto/CommonTypesDto.ts
frontend/src/helpers/DataConversors.ts
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/tests/unittests/helpers/DataConversors.spec.ts

- Worked on FSADT1-972
- Made the code DRY
- Made code reviews
---
[Backend](https://nr-forest-client-47-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-47-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-47-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-972: Submission (Blue Interface) Client Types

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
backend/src/test/java/ca/bc/gov/app/TestConstants.java

Also fixes FSADT1-969
Removing association from client type to BC registry data, as this does not match what we have in our database.
---
[Backend](https://nr-forest-client-49-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-49-legacy.apps.silver.devops.gov.bc.ca/) available

fix(FSADT1-981): fixing contact type association

---

frontend/package-lock.json
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/stub/mappings/fam.json

Fixing an issue with the FE when no contact type is present.
---
[Backend](https://nr-forest-client-12-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-12-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-12-legacy.apps.silver.devops.gov.bc.ca/) available

fix: fixing contact type issue

---

frontend/src/components/MainHeaderComponent.vue
frontend/src/routes.ts
frontend/tests/unittests/components/MainHeaderComponent.spec.ts

- When the current page is the Confirmation page (form-submitted):
- Logs out without showing the logout modal;
- Otherwise:
- Shows the logout modal as usual.
---
[Backend](https://nr-forest-client-21-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-21-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-21-legacy.apps.silver.devops.gov.bc.ca/) available

feat: add condition to show the logout modal

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
.github/workflows/unit-tests.yml
frontend/tests/components/components/grouping/AddressGroupComponent.cy.ts

---
[Backend](https://nr-forest-client-37-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-37-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-37-legacy.apps.silver.devops.gov.bc.ca/) available

chore: updating coverage report for frontend

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

Birthdate validation needs to be skipped when that field is not shown.
The value didn't get updated because the values which the `computed` `showBirthDate` depends on don't happen to change when the business is not found.
It was fixed by allowing that validation to get initialized with true.
---
[Backend](https://nr-forest-client-8-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-8-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-8-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

fix: skip birthdate validation when business is not found

---

processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceService.java
processor/src/test/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceServiceTest.java

fixing a loop condition due to the difference between case
---
[Backend](https://nr-forest-client-13-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-13-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-13-legacy.apps.silver.devops.gov.bc.ca/) available

fix(FSADT1-1049): fixing a loop condition on contact creation

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/components/forms/RadioInputComponent.vue
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue

- Removes "All fields are required"
- Adds "(required)" to all input field labels
Fixes [FSADT1-1021](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1021)
---
[Backend](https://nr-forest-client-11-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-11-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-11-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1021] Remove "All fields are required" and add "(required)" to all input field labels

---

frontend/src/App.vue
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/tests/unittests/pages/bceidform/ContactWizardStep.spec.ts

- Displays email in bold style
- Updates deletion toast messages
Fixes [FSADT1-1023](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1023), [FSADT1-1024](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1024)
---
[Backend](https://nr-forest-client-14-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-14-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-14-legacy.apps.silver.devops.gov.bc.ca/) available

fix(FSADT1-1023|FSADT1-1024): updating ui style

---

backend/src/main/java/ca/bc/gov/app/converters/EmailLogEntityJsonConvert.java
backend/src/main/java/ca/bc/gov/app/converters/SubmissionMatchDetailEntityBeforeConvert.java
backend/src/main/java/ca/bc/gov/app/job/ches/ChesEmailResendJob.java
backend/src/main/resources/db/migration/V1__initializing_data.sql

---
[Backend](https://nr-forest-client-21-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-21-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-21-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-961: Code reviews

---

frontend/src/helpers/validators/BCeIDFormValidations.ts
frontend/src/helpers/validators/GlobalValidators.ts
frontend/src/helpers/validators/SubmissionValidators.ts
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

---
[Backend](https://nr-forest-client-25-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-25-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-25-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1053: Improve validation when values are empty

---

frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCSCPage.vue

Adjust breakpoint styles for the BCSC form.
Most notably for the Small breakpoint regarding the following items:
- The read-only section;
- All the confirmation modals.
Apart from the Small breakpoint, the confirmation modals were updated for all other breakpoints to a fixed width of 40 rem (640 pixels). And this includes all the pages: BCSC form, BCeID form and Review new client.
Fixes [FSADT1-1058](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1058)
---
[Backend](https://nr-forest-client-26-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-26-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-26-legacy.apps.silver.devops.gov. …

[FSADT1-1058] BCSC form breakpoints

---

frontend/src/pages/FormBCSCPage.vue

- Tracks the validation status of form;
- Enables/disables the submit button in response to that validation status;
- Shows instruction message and tooltip when disabled.
Fixes [FSADT1-1050](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1050)
---
[Backend](https://nr-forest-client-29-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-29-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-29-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1050] Adjust "Submit application" button

---

backend/src/main/java/ca/bc/gov/app/filter/CorsWebFilter.java

---
[Backend](https://nr-forest-client-38-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-38-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-38-legacy.apps.silver.devops.gov.bc.ca/) available

fix(FSADT1-1082): Missing or insecure "X-Content-Type-Options" header

---

frontend/tests/components/components/grouping/ContactGroupComponent.cy.ts
frontend/tests/unittests/components/forms/DateInputComponent.spec.ts

---
[Backend](https://nr-forest-client-3-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-3-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-3-legacy.apps.silver.devops.gov.bc.ca/) available

test: fix test on CI

---

frontend/cypress/e2e/FormBCSCPage.cy.ts
frontend/src/assets/styles/global.scss
frontend/src/components/MainHeaderComponent.vue
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormSubmittedPage.vue
frontend/src/pages/SubmissionListPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue

Replaces tags with heading styles with a heading tag ( such h1, h2, h3, etc), following the definitions in the description of the ticket.
Please see also the comment in the ticket regarding fluid-heading styles.
Fixes [FSADT1-1040](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1040)
---
[Backend](https://nr-forest-client-9-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-9-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-9-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/workflow …

[FSADT1-1040] Apply HTML heading tags to heading styles for Accessibility

---

frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/tests/components/components/grouping/AddressGroupComponent.cy.ts
frontend/tests/components/components/grouping/ContactGroupComponent.cy.ts

Prevents messing with scroll position since a scroll move is also triggered from the parent component.
For both Address and Contacts steps.
Fixes [FSADT1-1079](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1079)
---
[Backend](https://nr-forest-client-8-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-8-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-8-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1079] Contacts page title is initially not visible

---

frontend/src/assets/styles/global.scss
frontend/src/components/forms/TextInputComponent.vue
frontend/src/pages/SubmissionReviewPage.vue

Prevents the body of the modal from taking more space than it should by keeping its code simple, without having to set its height. This was possible by making the "Matching client number" field always take the amount of space it needs, even when it's not visible, by using `visibility: hidden`.
Fixes [FSADT1-1102](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1102)
---
[Backend](https://nr-forest-client-22-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-22-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-22-legacy.apps.silver.devops.gov.bc.ca/) available
Once merged, code will be promoted and handed off to following …

[FSADT1-1102] Can not click button in Accept/Reject (using Edge)

---

frontend/cypress/fixtures/business.json
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/stub/__files/response-autocomplete.json
frontend/stub/mappings/backend.json
frontend/tests/pages/bceid/BusinessInformationWizardStep.cy.ts

- Adds a new error message for Unsupported client type (FSADT1-1108);
- Updates the error message for Unknown sole proprietor (FSADT1-1109).
Fixes [FSADT1-1108](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1108) and [FSADT1-1109](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1109).
---
[Backend](https://nr-forest-client-28-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-28-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-28-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/w …

[FSADT1-1108] [FSADT1-1109] Display Business error messages

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
backend/src/main/resources/db/migration/V4_submission_matching_detail_size.sql
backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/rejection.html

---
[Backend](https://nr-forest-client-29-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-29-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-29-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1116: Right client name in template

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
frontend/src/pages/SubmissionReviewPage.vue

---
[Backend](https://nr-forest-client-37-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-37-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-37-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1138: Adjust "auto approved" notification message for Individuals and Unregistered Sole proprietorship

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/dto/submissions/SubmissionBusinessDto.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/SubmissionReviewPage.vue
frontend/stub/__files/response-submissions-details-reviewedapproved.json
frontend/stub/__files/response-submissions-details-unregistered.json

---
[Backend](https://nr-forest-client-40-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-40-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-40-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1120: Add DOB for Individuals

---

backend/src/main/java/ca/bc/gov/app/validator/client/ClientAddressDtoValidator.java
frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/services/ForestClientService.ts

- Improved error messages to be meaningful to the user
- Fixed validation to allow US zip code format
---
[Backend](https://nr-forest-client-43-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-43-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-43-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1147: Fixed validation to allow US zip code format

---

frontend/cypress/e2e/SubmissionReviewPage.cy.ts
frontend/src/pages/SubmissionReviewPage.vue

Prevents a second click on the approve/reject buttons by disabling the buttons.
Reenables the buttons when the request to approve/reject gets responded. Useful when the request failed (error response), so the user can try again.
---
[Backend](https://nr-forest-client-13-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-13-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-13-legacy.apps.silver.devops.gov.bc.ca/) available

fix: prevent multiple clicks on the approve/reject buttons

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
database/openshift.dev.yml
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java

Adding specific deployment to update data on non-production environments
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/)

fix(FSADT1-1196): adding deployment to update division email

---

frontend/cypress/e2e/SubmissionReviewPage.cy.ts
frontend/src/pages/SubmissionReviewPage.vue

feat(fe:FSADT1-1215): Changes in the accept/reject buttons

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/components/forms/DropdownInputComponent.vue

Sets a white-space as helper-text when none (or empty one) is provided. This is a workaround to make the error message (invalid-text) be effectively displayed.
It was also attempted to downgrade back to Carbon 2.0, but the issue was already there.
Fixes [FSADT1-1225](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1225).
---

fix(fe:FSADT1-1225): display error message on dropdown

---

frontend/src/components/forms/DateInputComponent/DateInputPart.vue
frontend/src/components/forms/TextInputComponent.vue
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/stub/mappings/backend.json

Uses inputmode="numeric" instead of type="tel", unless the field indeed refers to a telephone value.
This prevents screen readers from announcing the field as a telephone when it's not.
---
---
Once merged, code will be …

fix(fe:FSADT1-1006): Display numeric keyboard without classifying the field as a telephone

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/components/forms/DateInputComponent/DateInputPart.vue
frontend/src/components/forms/DateInputComponent/index.vue
frontend/src/components/forms/DropdownInputComponent.vue
frontend/src/components/forms/TextInputComponent.vue
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

Adds required input purpose information as autocomplete attributes.
Note 1: the purpose token should be set only for information about the user who is filling the form. Otherwise we use either "off" to make it clear this is not about the end user (the user who is filling the form in) - for example, information about additional contacts - or we just omit it - we do it when the field has no matching purpose in the list of [Input Purposes for User Interface Components](https://www.w3.org/TR/WCAG21/#input-purposes).
Note 2: for fields where the data may or may not be about the end user - in case the user filling in is an agent, the address is not about him/her at all - the purpose was kept anyway, since it would be useful in case the user filling in is the proprietary, and the agent in turn …

feat(fe:FSADT1-1257): add required input purpose information

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
frontend/src/pages/SubmissionListPage.vue

The order of the results was different each time due to the nature of the flatMap operator. The flatMap operator merges the emissions of publishers, so they may interleave. This means it doesn't guarantee the order of execution. Because the order of the results matters, the operator was switched to flatMapSequential, as this operator preserves the order of the results.
---
- [Merge …

fix(be:FSADT1-1194): Fix sorting issue

---

.github/pull_request_template.md
backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java

Updating authorization documentation to match the roles.
---

docs(FSADT1-1274): updating the authorization doc

---

backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java

Adding a more granular pathmatching by setting the HTTP method that is allowed for each path
---

fix(FSADT1-1275): filtering access by http method

---

backend/openshift.deploy.yml
backend/src/main/java/ca/bc/gov/app/service/ches/ChesService.java
backend/src/test/java/ca/bc/gov/app/controller/ches/ChesControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/service/ches/ChesServiceIntegrationTest.java

feat(FSADT1-1280): rate-limit for backend

---

frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/tests/pages/bceid/BusinessInformationWizardStep.cy.ts

Remembers the status of individual validation so the button Next stays enabled when the user goes back to step 1.
Also makes sure it gets revalidated if a different individual business gets selected or type of business is changed to Unregistered.
Fixes [FSADT1-1283](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1283)
---
- [Merge …

fix(fe:FSADT1-1283): keep the button Next enabled on step 1

---

backend/openshift.deploy.yml

increasing rate limiter due to autocomplete issues
---

fix(FSADT1-1290): increasing rate limiter

---

frontend/package.json
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/composables/useFetch.ts
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/tests/unittests/composables/useFetch.spec.ts

- Allows to disable fetch's default error handling;
- Allows to call the default error handling manually;
- Updates calls.
Also applies a fix similar to #922 so to validate individual on the BCSC form.
---
---
Any successful …

fix(fe): fetch default error handling

---

backend/src/main/java/ca/bc/gov/app/util/JwtPrincipalUtil.java
frontend/src/helpers/ForestClientUserSession.ts
frontend/stub/mappings/fam.json

Names do not match on different emails, due to the way the backend and the frontend acquire the logged user's first and last name. Fixed that by making both algorithms match.
---

fix(FSADT1-1333): fixing client name on mail

---

backend/src/main/resources/application.yml
backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/registration.html
backend/src/main/resources/templates/rejection.html
frontend/cypress/e2e/FormBCSCPage.cy.ts
frontend/cypress/e2e/FormStaffPage.Submission.cy.ts
frontend/cypress/e2e/SubmissionReviewPage.cy.ts
frontend/src/components/forms/TextInputComponent.vue
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/helpers/validators/BCeIDFormValidations.ts
frontend/src/pages/FormStaffProcessingPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/routes.ts
frontend/tests/components/components/grouping/AddressGroupComponent.cy.ts
frontend/tests/components/components/grouping/ContactGroupComponent.cy.ts
frontend/tests/components/components/grouping/StaffLocationGroupComponent.cy.ts
frontend/tests/unittests/pages/FormStaffProcessingPage.spec.ts
legacy/src/main/java/ca/bc/gov/app/service/ClientLocationService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyService.java
processor/src/main/resources/application.yml

fix: small adjustments

---

processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyIndividualPersistenceService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyService.java
processor/src/test/java/ca/bc/gov/app/service/legacy/LegacyIndividualPersistenceServiceTest.java

fix(be:FSADT1-1419): Client ID is not being saved

---

frontend/components.d.ts
frontend/cypress/e2e/FormStaffPage.Submission.cy.ts
frontend/cypress/e2e/FormStaffPage.cy.ts
frontend/src/assets/styles/global.scss
frontend/src/components/grouping/FuzzyMatchNotificationGroupingComponent.vue
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/FormStaffPage.vue
frontend/stub/mappings/fuzzy_matches.json

Creates the Fuzzy Matching notification component, adds it to to the Staff form and calls it from the Individual business step - but not fully complete and without tests.
---

feat: add fuzzy matching notification

---

frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue
frontend/src/pages/staffform/CombinedClientInformationWizardStep.vue
frontend/src/pages/staffform/FirstNationClientInformationWizardStep.vue

fix(fe): Added missing masks

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/components/forms/DateInputComponent/index.vue
frontend/src/components/forms/DropdownInputComponent.vue
frontend/src/components/forms/MultiselectInputComponent.vue
frontend/src/components/forms/RadioInputComponent.vue
frontend/src/components/forms/TextInputComponent.vue
frontend/src/components/forms/TextareaInputComponent.vue
frontend/src/helpers/validators/StaffFormValidations.ts
frontend/src/helpers/validators/SubmissionReviewValidations.ts
frontend/src/helpers/validators/SubmissionValidators.ts
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormStaffPage.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue
frontend/src/pages/staffform/IndividualClientInformationWizardStep.vue
frontend/src/pages/staffform/ReviewWizardStep.vue

Changing the way the next call to validate works. Now, the validation will happen inside each component, by triggering the revalidationBus. With the current change, it will emit an event that can be either undefined or a list of keys.
The keys are a list of IDs of fields that need to be triggered to call the revalidate. This will prevent the next step from triggering the validation and showing with error even before showing up.
This will also take care of dynamic or changing validators. We will have to use when required the same strategy used for postal codes for example.
--- …

fix(FSADT1-1435): fixing validation during onnext

---

backend/src/main/java/ca/bc/gov/app/controller/client/ClientCodesController.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
frontend/cypress/e2e/FormStaffPage.cy.ts
frontend/cypress/fixtures/provinceCodeBC.json
frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/staffform/IndividualClientInformationWizardStep.vue
frontend/src/pages/staffform/ReviewWizardStep.vue
frontend/stub/__files/response-province-CA-BC.json
frontend/stub/mappings/codes.json

feat(FSADT1-1439|FSADT1-1441): Review page updates

---

frontend/src/components/grouping/StaffContactGroupComponent.vue
frontend/src/components/grouping/StaffLocationGroupComponent.vue

When there is a unique validation in the front-end, unrelated inputs were displayed as invalid.
- On the Locations step (unique location name), the Notes input was also displayed as invalid;
- On the Contacts step (unique contact name - first name and last name), the Location name input was also displayed as invalid.
---
- [Merge …

fix(fe): remove unrelated error-message from inputs

---

frontend/cypress/e2e/pages/FormStaffPageFuzzy.cy.ts
frontend/cypress/fixtures/fuzzy/document_and_partial_individual_match.json
frontend/cypress/fixtures/fuzzy/full_and_partial_individual_match.json
frontend/package.json
frontend/src/components/grouping/FuzzyMatchNotificationGroupingComponent.vue
frontend/stub/__files/fuzzy/document_and_partial_individual_match.json
frontend/stub/__files/fuzzy/full_and_partial_individual_match.json
frontend/stub/mappings/fuzzy_matches.json
frontend/tests/unittests/components/grouping/FuzzyMatchNotificationGroupingComponent.spec.ts

When a field has both a full (error) and a partial (warning) match, render the field using the error style.
Also renames some stubs to make it clearer.
---
---
Any successful deployments (not always required) will be available …

fix(fe): display simultaneous error and warning

---

frontend/cypress/support/commands.ts
frontend/cypress/support/cypress.d.ts
frontend/src/pages/staffform/IndividualClientInformationWizardStep.vue
frontend/tests/components/pages/staffform/IndividualClientInformationWizardStep.cy.ts

Revalidates the id number after changing the province, so the button next is kept enabled if the supplied id number is valid for the newly selected province.
Fixes [FSADT1-1448](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1448)
---
---
Deployments, as required, will be …

fix(fe: FSADT1-1448): Button Next gets disabled if the Province is changed

---

.github/workflows/pr-open.yml
processor/src/main/java/ca/bc/gov/app/ApplicationConstant.java
processor/src/main/java/ca/bc/gov/app/dto/SubmissionProcessKindEnum.java
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionAutoProcessingService.java
processor/src/main/java/ca/bc/gov/app/service/processor/ProcessorService.java

- Added filter only to allow hot requests to proceed
- Added hot/cold filter to the processor
This change will check if a submission is HOT or COLD.
A HOT submission can be processed, by checking if the timing of processing is bigger than 2 minutes.
A COLD submission is being processed already, and we check that by the processing time if it is smaller than 2 minutes.
---
- [Merge …

fix(FSADT1-1483): updated filter of hot/cold requests

---

backend/src/main/java/ca/bc/gov/app/validator/address/AddressAddressValidator.java
backend/src/main/java/ca/bc/gov/app/validator/address/AddressComplementaryInformationValidator.java
backend/src/main/java/ca/bc/gov/app/validator/address/AddressNameValidator.java
backend/src/test/java/ca/bc/gov/app/validator/address/AddressAddressValidatorTest.java
backend/src/test/java/ca/bc/gov/app/validator/address/AddressComplementaryInformationValidatorTest.java
frontend/src/helpers/validators/BCeIDFormValidations.ts
frontend/src/helpers/validators/StaffFormValidations.ts

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/)

feat(FSADT1-1497): Adjust character limit of Street address field

---

frontend/openshift.configmap.dev.yml
frontend/openshift.configmap.test.yml
frontend/package.json
frontend/src/components/MainHeaderComponent.vue
frontend/src/routes.ts

chore: Removed STAFF_CREATE temporary flag

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/pages/staffform/FirstNationClientInformationWizardStep.vue
frontend/tests/unittests/components/forms/AutoCompleteInputComponent.spec.ts

Prevents the Autocomplete component from re-emitting with value undefined after a selection.
Fixes [FSADT1-1427](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1427)
---

fix(fe: FSADT1-1427): Autocomplete emitting value twice

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
processor/src/main/java/ca/bc/gov/app/ApplicationConstant.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyRegisteredSPPersistenceService.java
processor/src/test/java/ca/bc/gov/app/service/legacy/LegacyRegisteredSPPersistenceServiceTest.java

- added to external users the DBA field filled
- fixed the DBA field on the processor
---

fix(FSADT1-1514): fixed doing business as processing

---

frontend/cypress/e2e/pages/staffform/BcRegisteredClientInformationWizardStep.cy.ts
frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

Clears all the business information when a new Client name gets selected.
Fixes [FSADT1-1511](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1511)
---

fix(fe: FSADT1-1511): Clear business information when a new Client name gets selected

---

frontend/cypress/e2e/pages/staffform/BcRegisteredClientInformationWizardStep.cy.ts
frontend/cypress/support/cypress.d.ts
frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

- Requires Date of birth before enabling the button Next;
- Resets the validation for BcRegisteredClientInformationWizardStep when the selected Client name changes.
This prevents getting into a state where user can't proceed to the Next step.
Fixes [FSADT1-1508](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1508)
---
- [Merge …

fix(fe:FSADT1-1508): reset validation when the selected Client name changes

---

frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

Prevents the error message on Date of birth which appears when a Sole proprietorship that "already exists" or is "not owned by a person" gets selected, by waiting to render the Date of birth field after the client data is returned, like we do for all the other fields.
(This addresses the Note 2 on FSADT1-1508. The main fixes PR for FSADT1-1508 - #1191 - are already merged)
Fixes [FSADT1-1508](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1508)
---
- [Analysis Workflow](https://github.com/bcgov/nr-forest-client/actions/wo …

fix(fe:FSADT1-1508): prevent error on Date of birth before using it

---

legacy/src/main/java/ca/bc/gov/app/controller/ClientSearchController.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java
legacy/src/test/java/ca/bc/gov/app/service/ClientSearchServiceIntegrationTest.java

Updated predictive endpoint to be able to run both predictive and full search as both results are the same.
- Updated endpoint to be just search (/api/search)
- Updated the controller to be able to search for the latest
- Updated query to include pagination
- Added default page values for predictive
- Changed tests
---
- [Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/wo …

feat(FSADT1-1528): updating complex search from predictive

---

legacy/src/main/java/ca/bc/gov/app/controller/ClientSearchController.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java
legacy/src/test/java/ca/bc/gov/app/service/ClientSearchServiceIntegrationTest.java

Added the count for the predictive and full query that were missing
---

fix(FSADT1-1528): added missing count

---

frontend/src/pages/SearchPage.vue

feat(fe:FSADT1-1541): Display an error message when the BE is down

---

frontend/cypress/e2e/pages/SearchPage.cy.ts
frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/tests/unittests/components/forms/AutoCompleteInputComponent.spec.ts

This is a fix for #1223.
Stops preventing the action to clear the input value when preventSelection is true.
And also fixes tests that broke after updates on feat/client3.
Fixes [FSADT1-1521](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1521)
---

fix(fe:FSADT1-1521): clear the AutoComplete field when preventSelection is true

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java
frontend/cypress/support/commands.ts
frontend/src/pages/SearchPage.vue

feat(FSADT1-1525): Add FAM role CLIENT_SUSPEND

---

frontend/cypress/e2e/pages/SearchPage.cy.ts
frontend/src/pages/SearchPage.vue

Validates the search on press enter.
---

fix(fe): validate search on press enter

---

frontend/cypress/e2e/pages/SearchPage.cy.ts
frontend/src/pages/SearchPage.vue

Displays predictive results in Title Case.
Also limits predictive search to 5 results.
Fixes [FSADT1-1549](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1549)
---

feat(fe:FSADT1-1549): displays predictive results in Title Case

---

frontend/src/components/DataFetcher.vue
frontend/src/pages/SearchPage.vue
frontend/tests/unittests/components/DataFetcher.spec.ts

- Clears old search results when a new search starts;
- Discards the response from old requests, i.e. once a new request starts, any previous ongoing requests get dismissed.
Fixes [FSADT1-1566](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1566)
---

feat(fe:FSADT1-1566): Clear predictive search results whenever input changes

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
database/openshift.backup.yml
database/openshift.deploy.yml
database/openshift.dev.yml

Replaces deprecated Deployment Configs with Deployments. Also removes image streams and uses a randomly generated envar to ensure consistent rollouts.
Unfortunately there will be some downtime when this deploys.
Steps:
- Delete deployment configs and services for TEST database and backend
- Delete deployment configs and services for PROD database and backend
- Merge this PR
- Let deployments to TEST and PROD complete
Part of #1123.
---
- [Analysis Workflow](https://github.com/bcgov/nr-forest-client/actions/workflows/analysis …

ci!: deprecate deployment config, remove image stream - db only

---

frontend/src/assets/styles/global.scss
frontend/src/pages/SearchPage.vue
frontend/src/pages/SubmissionListPage.vue

Adjusts column widths in a responsive manner and uses a small min-width for the search data-table so it doesn't need the horizontal scroll until the screen goes below 1280px.
---

feat(fe): adjust search table column widths

---

backend/src/main/java/ca/bc/gov/app/converters/ForestClientObfuscate.java
backend/src/main/java/ca/bc/gov/app/dto/legacy/ForestClientDetailsDto.java
backend/src/test/java/ca/bc/gov/app/converters/ForestClientObfuscateTest.java
backend/src/test/java/ca/bc/gov/app/service/client/ClientServiceIntegrationTest.java
frontend/src/pages/client-details/SummaryView.vue
legacy/src/main/java/ca/bc/gov/app/dto/ForestClientDetailsDto.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java

fix: fixing data loading due to date type

---

backend/src/main/java/ca/bc/gov/app/dto/legacy/ForestClientContactDto.java
backend/src/main/java/ca/bc/gov/app/repository/client/ContactTypeCodeRepository.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientCodeService.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
backend/src/test/java/ca/bc/gov/app/service/client/ClientServiceIntegrationTest.java
frontend/cypress/e2e/pages/SearchPage.cy.ts
frontend/src/pages/ClientDetailsPage.vue
frontend/src/pages/SearchPage.vue
frontend/src/pages/client-details/ContactView.vue
frontend/src/pages/client-details/LocationView.vue
frontend/tests/components/pages/client-details/ContactView.cy.ts
frontend/tests/components/pages/client-details/LocationView.cy.ts

Fixing missing parameter issues. Added the load process for the contact code description as required by FSADT1-1595
---

fix(FSADT1-1595): fixing missing contact code desc

---

frontend/tests/unittests/services/ForestClientService.spec.ts

Adds missing tests for function formatPhoneNumber.
---

test(fe): format phone number

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
backend/openshift.deploy.yml
frontend/openshift.deploy.yml

Split the default route off from the vanity URL so that workflows and deployments can happen without overwriting TEST and PROD routes with certificates.
Remove backend route, which isn't in use.
---

chore(ci): route update

---

.github/workflows/.tools-cleanup.yml
.github/workflows/.tools-deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

Use bcgov/action-oc-runner instead of redhat-actions/openshift-tools-installer, which is infrequently maintained and has slowdown issues.
---

chore(ci): bcgov/action-oc-runner

---

backend/openshift.deploy.yml
frontend/openshift.deploy.yml
legacy/openshift.deploy.yml
legacydb/openshift.deploy.yml
processor/openshift.deploy.yml

Removed by OCIO platform team.  We're just following their lead.
---

chore(ci): deprecate openshift resource limits

---

frontend/cypress/e2e/pages/ClientDetailsPage.cy.ts
frontend/src/components/grouping/StaffContactGroupComponent.vue
frontend/src/pages/ClientDetailsPage.vue
frontend/src/pages/client-details/ContactView.vue
frontend/src/services/ForestClientService.ts
frontend/stub/__files/response-clients-details-SE.json
frontend/tests/components/components/grouping/StaffContactGroupComponent.cy.ts
frontend/tests/components/pages/client-details/ContactView.cy.ts
frontend/tests/unittests/services/ForestClientService.spec.ts

Includes the location code in the locations titles in the options of the Associated locations input, but only on the Client Details page.
ie: instead of "Mailing address", shows "00 - Mailing address".
On the other hand, when location name is empty shows it like: "00".
Fixes [FSADT1-1761](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1761)
---
- [Merge …

feat(fe:FSADT1-1761): Contacts - on Edit associated locations is missing

---

.github/workflows/.tools-cleanup.yml
.github/workflows/.tools-deploy.yml
frontend/junk.txt

Tools namespace had been filling up. This should help.
Replaces #1533
---
---
Please …

chore(ci): scale down legacydb before removing PR db 

---

.github/workflows/pr-close.yml
.github/workflows/scheduled.yml

This PR adjusts the CI workflow versions to fix version inconsistencies.
- Downgrades the schema-spy workflow version from v0.10.0 to v0.9.0.
- Downgrades the pr-close workflow version from v0.10.0 to v0.9.0.
---
---
Any successful …

ci: fixing version

---

legacy/src/main/java/ca/bc/gov/app/service/ClientService.java

Due to incorrect or records with same timestamps and based on business requirements, 
when client information is selected, the "Client created" record must appear 
as the last entry in the sorted history log.
---

fix(be:FSADT1-1775): Ensure "Client created" record appears last

---

frontend/src/assets/styles/global.scss
frontend/src/pages/client-details/HistoryView.vue
frontend/src/services/ForestClientService.ts
frontend/stub/__files/response-client-history-source-LOC.json
frontend/stub/__files/response-client-history.json
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientQueries.java

- Adjusted address lines to be displayed as a group as per requested by Ziad
- Distinguished between zip code and postal code for labels
---

feat(FSADT1-1855): Adjusted address lines to be displayed as a group

---

backend/src/main/java/ca/bc/gov/app/configuration/ForestClientMetricConfiguration.java

This PR updates the histogram configuration for metrics by replacing the previous percentile-histogram toggle with explicit service-level objective (SLO) durations in nanoseconds.
- Switched from `.percentilesHistogram(true)` to a series of `serviceLevelObjectives(...)` durations.
- Added `java.time.Duration` import to calculate nanosecond values.
- Defined SLO boundaries at various latency thresholds (100 ms up to 1 min).
--- …

fix(metrics): fixing some of the metrics histogram values
