.github/workflows/pr-close.yml
.github/workflows/pr-open.yml

Changes:
- removed main merge PR comments
- removed deployment confirmation PR comments
- added PR description message w/ same info
---
[Backend](https://nr-forest-client-85-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-85-frontend.apps.silver.devops.gov.bc.ca/) available

Replace noisy PR comments with PR description add

---

.github/workflows/pr-open.yml
frontend/index.html

---
[Backend](https://nr-forest-client-88-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-88-frontend.apps.silver.devops.gov.bc.ca/) available

Secret scanning in PR workflow

---

backend/Dockerfile
frontend/Dockerfile

Fix Trivy security alerts.
---
[Backend](https://nr-forest-client-104-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-104-frontend.apps.silver.devops.gov.bc.ca/) available

Address four Trivy security alerts in Dockerfiles

---

.github/dependabot.yml

Dependabot.yml to automatically receive PRs with dependency and GitHub Actions updates.
---
[Backend](https://nr-forest-client-106-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-106-frontend.apps.silver.devops.gov.bc.ca/) available

Auto dependency updates for maven, npm and actions

---

backend/openshift.deploy.yml
database/openshift.deploy.yml
frontend/openshift.deploy.yml

Project running out of memory.  Allocations seem high.
---
[Backend](https://nr-forest-client-120-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-120-frontend.apps.silver.devops.gov.bc.ca/) available

Dial down resources and clean up templates

---

database/openshift.deploy.yml
frontend/openshift.deploy.yml

Continue adjusting resources.
---
[Backend](https://nr-forest-client-126-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-126-frontend.apps.silver.devops.gov.bc.ca/) available

Dial down cpu for db and frontend

---

frontend/package-lock.json
frontend/package.json

---
[Backend](https://nr-forest-client-130-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-130-frontend.apps.silver.devops.gov.bc.ca/) available

Dependabot/npm and yarn/frontend/vue tsc 1.0.11

---

database/Dockerfile
database/openshift.deploy.yml

Change anything to kick off a build.
---
[Backend](https://nr-forest-client-135-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-135-frontend.apps.silver.devops.gov.bc.ca/) available

Cleanup Dockerfile

---

.github/workflows/merge-main.yml

GHCR cleanup removed, breaks w/ new naming.  Need to find or create a replacement.
---
[Backend](https://nr-forest-client-138-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-138-frontend.apps.silver.devops.gov.bc.ca/) available

Remove GHCR cleanup, breaks w/ new naming

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml
backend/package-lock.json
common/openshift.init.yml
database/openshift.deploy.yml

---
[Backend](https://nr-forest-client-139-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-139-frontend.apps.silver.devops.gov.bc.ca/) available

Init for secrets and network policies

---

.github/workflows/merge-main.yml

Bug: PROD db tag off.
---
[Backend](https://nr-forest-client-141-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-141-frontend.apps.silver.devops.gov.bc.ca/) available

Fixed PROD db tag

---

frontend/openshift.deploy.yml

Fix configmaps.  Part of workflow overhaul.
---
[Backend](https://nr-forest-client-169-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-169-frontend.apps.silver.devops.gov.bc.ca/) available

Load already existing configmap

---

.github/workflows/merge-main.yml
backend/openshift.deploy.yml
frontend/openshift.deploy.yml
frontend/src/main.ts

- fix frontend pipeline runtime env problem for login
- decrease initial delay of readiness check in backend pipeline to decrease the time cost for backend deployment
- increase probe failure threshold to reduce unnecessary rejections
---
[Backend](https://nr-forest-client-179-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-179-frontend.apps.silver.devops.gov.bc.ca/) available

Merge to main: add missing keycloak client id to frontend pipeline

---

.github/workflows/unit-tests.yml

---
[Backend](https://nr-forest-client-178-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-178-frontend.apps.silver.devops.gov.bc.ca/) available

Use bcgov-nr/action-test-and-analyse-java

---

backend/pom.xml
backend/src/main/java/ca/bc/gov/app/core/configuration/SwaggerConfiguration.java
backend/src/main/java/ca/bc/gov/app/core/controller/CoreController.java
backend/src/main/java/ca/bc/gov/app/m/ches/controller/ChesCommonServicesController.java
backend/src/main/java/ca/bc/gov/app/m/ob/controller/OrgBookApiController.java
backend/src/main/java/ca/bc/gov/app/m/ob/service/impl/OrgBookApiServiceImpl.java
backend/src/main/java/ca/bc/gov/app/m/om/controller/OpenMapsController.java
backend/src/main/java/ca/bc/gov/app/m/om/service/impl/OpenMapsServiceImpl.java
backend/src/main/java/ca/bc/gov/app/m/oracle/legacyclient/controller/LegacyClientController.java
backend/src/main/java/ca/bc/gov/app/m/oracle/legacyclient/service/impl/LegacyClientServiceImpl.java
backend/src/main/java/ca/bc/gov/app/m/postgres/client/controller/ClientController.java
backend/src/main/java/ca/bc/gov/app/m/postgres/client/service/impl/ClientServiceImpl.java
backend/src/main/resources/application.properties

---
[Backend](https://nr-forest-client-181-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-181-frontend.apps.silver.devops.gov.bc.ca/) available

Close #165: Fix swagger in backend for sprint boot 3

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml

Fixing an issue with deployment when merged to the main branch.
Same deployment has been tested during pull requests
---
[Backend](https://nr-forest-client-233-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-233-frontend.apps.silver.devops.gov.bc.ca/) available

fix: fixing deploy to main

---

frontend/src/common/examples/FormJsonSchemaExample.vue
frontend/src/common/examples/SingleFormComponentExample.vue

---
[Backend](https://nr-forest-client-256-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-256-frontend.apps.silver.devops.gov.bc.ca/) available

Frontend: Renamed some names and files

---

frontend/src/common/examples/SingleFormComponentExample.vue

---
[Backend](https://nr-forest-client-269-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-269-frontend.apps.silver.devops.gov.bc.ca/) available

fix(fe): frontend fix

---

backend/src/main/java/ca/bc/gov/app/routes/client/ClientRouter.java
backend/src/test/java/ca/bc/gov/app/endpoints/client/ClientHandlerIntegrationTest.java

---
[Backend](https://nr-forest-client-296-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-296-frontend.apps.silver.devops.gov.bc.ca/) available

Backend Improvements

---

backend/src/main/resources/db/migration/V1__initializing_data.sql

---
[Backend](https://nr-forest-client-307-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-307-frontend.apps.silver.devops.gov.bc.ca/) available

Data model

---

backend/src/main/java/ca/bc/gov/app/configuration/WebfluxConfiguration.java
backend/src/main/resources/application.yml

---
[Backend](https://nr-forest-client-314-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-314-frontend.apps.silver.devops.gov.bc.ca/) available

feat(cors): adding cors support for webflux

---

backend/src/main/java/ca/bc/gov/app/dto/client/CountryCodeDto.java
backend/src/main/java/ca/bc/gov/app/entity/client/CountryCodeEntity.java
backend/src/main/java/ca/bc/gov/app/handlers/client/ClientCountryCodeHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/client/ClientTypeCodeHandler.java
backend/src/main/java/ca/bc/gov/app/repository/client/CountryCodeRepository.java
backend/src/main/java/ca/bc/gov/app/routes/client/ClientRouter.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
backend/src/test/java/ca/bc/gov/app/endpoints/client/ClientHandlerIntegrationTest.java

Implemented the country list API on the backend.
Fixes FSADT1-657
Implemented an integration test to validate pagination and data returned.
---
[Backend](https://nr-forest-client-322-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-322-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-322-legacy.apps.silver.devops.gov.bc.ca/) available

feat(be:FSADT1-657): adding country list api

---

frontend/src/common/FormSelect.vue
frontend/src/common/examples/SingleFormComponentExample.vue
frontend/src/core/FormType.ts
frontend/src/pages/applynewclient/formsections/FormSections.vue
frontend/src/pages/applynewclient/formsectionschemas/BusinessTypeSectionSchema.ts

- Added Client Types from backend
- Fixed typo in common component name
---
[Backend](https://nr-forest-client-324-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-324-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-324-legacy.apps.silver.devops.gov.bc.ca/) available

Frontend v0.1

---

backend/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
backend/src/main/java/ca/bc/gov/app/handlers/ches/ChesHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/client/ClientCountryCodeHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/client/ClientProvinceCodeHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/client/ClientTypeCodeHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/openmaps/OpenMapsHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/orgbook/OrgBookIncorporationHandler.java
backend/src/main/java/ca/bc/gov/app/handlers/orgbook/OrgBookNameHandler.java
backend/src/main/java/ca/bc/gov/app/routes/client/ClientRouter.java
backend/src/main/java/ca/bc/gov/app/service/orgbook/OrgBookApiService.java
backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/endpoints/client/ClientHandlerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/endpoints/orgbook/OrgBookHandlerIntegrationTest.java
backend/src/test/resources/application-default.yml
frontend/src/common/FormAutocomplete.vue
frontend/src/common/FormComponentOptions.vue
frontend/src/core/FormType.ts
frontend/src/pages/applynewclient/formsections/FormSections.vue
frontend/src/pages/applynewclient/formsectionschemas/InformationSectionSchema.ts
frontend/src/services/forestClient.service.ts

Implementing an autocomplete component that fetches from an external API.
FSADT1-655
For now, the autocomplete component contains a hardcoded fetch request to a specific URL. The `useFetch` request is a new function implemented to be used whenever required, but due to time constraints and the way the code is organized right now, I decided to keep it hard-coded. Next iteration will have a more flexible component for autocompletion.
Some fixes where applied to the backend component as well
---
[Backend](https://nr-forest-client-331-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-331-frontend.apps.silver. …

feat(fe:autocomplete): adding useFetch function

---

frontend/src/pages/applynewclient/formsections/FormSections.vue
frontend/src/pages/applynewclient/formsectionschemas/LocationSectionSchema.ts
frontend/src/pages/applynewclient/formvalidationrules/RequiredFields.ts

---
[Backend](https://nr-forest-client-338-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-338-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-338-legacy.apps.silver.devops.gov.bc.ca/) available

feat(fe): Added countries from BE

---

backend/src/main/java/ca/bc/gov/app/service/orgbook/OrgBookApiService.java
frontend/src/pages/applynewclient/formsections/FormSections.vue
frontend/src/services/FetchService.ts

saving the data we read from the autocomplete to be set into the incorporationNumber.
Not the best approach but it should work.
---
[Backend](https://nr-forest-client-351-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-351-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-351-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

feat: adding autocomplete code to model

---

frontend/src/services/ForestClientService.ts

Fixing backend URL acquisition. Changed from the actual VITE variable to the coreConstant
---
[Backend](https://nr-forest-client-416-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-416-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-416-legacy.apps.silver.devops.gov.bc.ca/) available

fix: fixing backend address acquisition

---

backend/openshift.deploy.yml
backend/src/main/java/ca/bc/gov/app/configuration/ForestClientConfiguration.java
backend/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
backend/src/main/java/ca/bc/gov/app/filter/CorsWebFilter.java
backend/src/main/resources/application.yml
frontend/.dockerignore
frontend/Caddyfile
frontend/Dockerfile
frontend/openshift.deploy.yml
frontend/public/data/config.js
frontend/src/core/CoreConstants.ts
frontend/src/pages/applyclientnumber/ApplyClientNumberPage.vue
frontend/src/services/ForestClientService.ts
legacy/openshift.deploy.yml

Changing the number of resources being used by the application in order to avoid the quota being exceeded.
Also, changed the frontend to match the [nr-quickstart-typescript repository](https://github.com/bcgov/nr-quickstart-typescript)
This will require monitoring for some time
---
[Backend](https://nr-forest-client-419-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-419-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-419-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

fix: fixing resource utilization

---

frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/pages/applyclientnumber/ApplyClientNumberPage.vue

---
[Backend](https://nr-forest-client-420-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-420-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-420-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-724 - Notified that a business is not in good standing

---

.github/workflows/merge-main.yml
backend/openshift.deploy.yml
frontend/openshift.deploy.yml
legacy/openshift.deploy.yml

---
[Backend](https://nr-forest-client-421-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-421-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-421-legacy.apps.silver.devops.gov.bc.ca/) available

chore: rearranging resources for openshift

---

backend/src/main/java/ca/bc/gov/app/validator/client/ClientAddressDtoValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientBusinessInformationDtoValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientContactDtoValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientLocationDtoValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitterInformationDtoValidator.java
backend/src/main/java/ca/bc/gov/app/validator/common/CommonValidator.java
backend/src/test/java/ca/bc/gov/app/endpoints/client/ClientSubmissionControllerIntegrationTest.java
frontend/components.d.ts
frontend/src/common/ValidationMessagesComponent.vue
frontend/src/pages/applyclientnumber/AddressComponent.vue
frontend/src/pages/applyclientnumber/ApplyClientNumberPage.vue
frontend/src/pages/applyclientnumber/ContactComponent.vue
frontend/src/pages/applyclientnumber/ContactSectionComponent.vue

- Fixed validation messages on the BE
- Fixed missing return in validation messages component
- Added missing validation in contacts section
- Refactored code in both FE and BE
- Beautified code
---
[Backend](https://nr-forest-client-427-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-427-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-427-legacy.apps.silver.devops.gov.bc.ca/) available

Validation fixes

---

backend/pom.xml

---
[Backend](https://nr-forest-client-432-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-432-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-432-legacy.apps.silver.devops.gov.bc.ca/) available

fix(be): Fixed pom file

---

backend/src/main/java/ca/bc/gov/app/dto/client/ClientBusinessInformationDto.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
backend/src/main/java/ca/bc/gov/app/util/ClientValidationUtils.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/RegisteredBusinessInformationValidator.java
backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/utils/ClientSubmissionAggregator.java
backend/src/test/resources/failValidationTest.csv

---
[Backend](https://nr-forest-client-446-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-446-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-446-legacy.apps.silver.devops.gov.bc.ca/) available

Update validations, ClientSubmissionDto and fix new submission status

---

backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/UnregisteredBusinessInformationValidator.java
backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java

Fix Unregistered Business validation, it was not being called correctly and caused the Registered Business validations to being run instead
Fixes #FSADT1-742
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
Previous tests were run and a new test was added for Unregistered Business case
---
[Backend](https://nr-forest-client-448-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-448-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-448-legacy.apps.silver.devops.gov.bc. …

Fix Unregistered Business validation scenario

---

backend/src/main/resources/db/migration/V1__initializing_data.sql
frontend/src/common/ValidationMessagesComponent.vue
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/pages/applyclientnumber/AddressComponent.vue
frontend/src/pages/applyclientnumber/ApplyClientNumberPage.vue
frontend/src/pages/applyclientnumber/ContactComponent.vue

---
[Backend](https://nr-forest-client-449-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-449-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-449-legacy.apps.silver.devops.gov.bc.ca/) available

Frontend Improvements

---

backend/src/main/java/ca/bc/gov/app/dto/client/ClientSubmissionDto.java
backend/src/main/java/ca/bc/gov/app/dto/client/ClientSubmitterInformationDto.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitterInformationDtoValidator.java
backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/utils/ClientSubmissionAggregator.java

Update SubmissionDto userId field is now nested in submitterInformation
Simple change placement of field in Submission DTO

[FSADT1-761] Update SubmissionDto userId field is now nested in submitterInformation

---

frontend/src/App.vue
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/pages/applyclientnumber/ApplyClientNumberPage.vue

---
[Backend](https://nr-forest-client-455-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-455-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-455-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-762

---

legacy/src/main/java/ca/bc/gov/app/service/ReportingClientService.java

Removing cronjob that generated the report
---
[Backend](https://nr-forest-client-457-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-457-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-457-legacy.apps.silver.devops.gov.bc.ca/) available

fix: removing cron from legacy

---

.github/workflows/unit-tests.yml

---
[Backend](https://nr-forest-client-479-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-479-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-479-legacy.apps.silver.devops.gov.bc.ca/) available

deps: update Trivy and rename parameter

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml

Removing vault due to inconsistency
---
[Backend](https://nr-forest-client-490-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-490-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-490-legacy.apps.silver.devops.gov.bc.ca/) available

fix: removing vault due to inconsistency

---

backend/src/main/resources/db/migration/V1__initializing_data.sql

Made a minor change in the DB as per suggested by the DBAs (FSADT1-796)
---
[Backend](https://nr-forest-client-493-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-493-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-493-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-796 - DB improvements

---

backend/src/main/resources/db/migration/V1__initializing_data.sql

---
[Backend](https://nr-forest-client-496-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-496-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-496-legacy.apps.silver.devops.gov.bc.ca/) available

(FSADT1-796) Changes in the DB

---

frontend/src/App.vue

---
[Backend](https://nr-forest-client-497-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-497-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-497-legacy.apps.silver.devops.gov.bc.ca/) available

Frontend fix

---

.github/workflows/merge-main.yml
.github/workflows/unit-tests.yml
backend/pom.xml
legacy/pom.xml
processor/pom.xml

Moving sonar parameters from pom to workflow
---
[Backend](https://nr-forest-client-512-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-512-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-512-legacy.apps.silver.devops.gov.bc.ca/) available

chore: fixing backend sonar parameters

---

.github/workflows/pr-open.yml

Thanks for testing out the rc for bcgov-nr/action-pr-description-add!  :)

Test bcgov-nr/action-pr-description-add rc

---

frontend/package-lock.json
frontend/package.json
frontend/tests/unittests/composables/useFetch.spec.ts

---
[Backend](https://nr-forest-client-530-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-530-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-530-legacy.apps.silver.devops.gov.bc.ca/) available

fix(fe): Test new library

---

frontend/tests/unittests/composables/useFetch.spec.ts

- Last attempt to solve the issue
---
[Backend](https://nr-forest-client-532-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-532-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-532-legacy.apps.silver.devops.gov.bc.ca/) available

fix: Solving FE unit testing issues

---

.github/workflows/merge-main.yml

---
[Backend](https://nr-forest-client-533-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-533-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-533-legacy.apps.silver.devops.gov.bc.ca/) available

fix: fixing merge main issues

---

.github/workflows/pr-open.yml
frontend/Dockerfile
frontend/package.json
frontend/src/CoreConstants.ts
frontend/src/components/MainHeaderComponent.vue

- FSADT1-840: Add environment and built version
Note: The built version part needs to be address in the future with the DevOps specialist. For now, this built version will be hardcoded.
---
[Backend](https://nr-forest-client-539-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-539-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-539-legacy.apps.silver.devops.gov.bc.ca/) available

feat(fe): FSADT1-840: Add environment and built version

---

.github/workflows/pr-open.yml
backend/pom.xml
frontend/nyc.config.json
frontend/package.json
legacy/pom.xml
processor/pom.xml

fixing frontend tests
---
[Backend](https://nr-forest-client-548-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-548-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-548-legacy.apps.silver.devops.gov.bc.ca/) available

ci: updating ci

---

.github/workflows/merge-main.yml
frontend/src/pages/ErrorPage.vue
frontend/src/pages/UserLoadingPage.vue

- Forced secrets overwrite
- Added error handling on frontend for no code
---
[Backend](https://nr-forest-client-550-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-550-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-550-legacy.apps.silver.devops.gov.bc.ca/) available

fix: small changes

---

.gitignore
legacy/src/main/resources/application.yml

---
[Backend](https://nr-forest-client-563-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-563-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-563-legacy.apps.silver.devops.gov.bc.ca/) available

fix(be): Updated backend port

---

backend/src/main/java/ca/bc/gov/app/service/ches/ChesService.java
backend/src/main/resources/application.properties
backend/src/main/resources/application.yml
backend/src/main/resources/templates/emailHead.html
frontend/src/routes.ts

---
[Backend](https://nr-forest-client-564-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-564-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-564-legacy.apps.silver.devops.gov.bc.ca/) available

fix(be): encoding

---

frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/tests/unittests/pages/bceidform/ContactWizardStep.spec.ts

---
[Backend](https://nr-forest-client-580-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-580-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-580-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-931] Deleting contact with null as firstName

---

frontend/components.d.ts
frontend/package-lock.json
frontend/package.json
frontend/src/helpers/validators/GlobalValidators.ts
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/tests/components/components/grouping/AddressGroupComponent.cy.ts
frontend/tests/unittests/pages/bceidform/ContactWizardStep.spec.ts

---
[Backend](https://nr-forest-client-588-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-588-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-588-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-931

---

frontend/src/assets/styles/global.scss

---
[Backend](https://nr-forest-client-587-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-587-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-587-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-884] Make progress step not look like a link

---

.github/workflows/pr-open.yml
frontend/openshift.deploy.yml

Fixing FE deployment parameters
---
[Backend](https://nr-forest-client-42-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-42-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-42-legacy.apps.silver.devops.gov.bc.ca/) available

fix: fixing deployment for FE

---

frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue
frontend/src/composables/useFetch.ts
frontend/src/helpers/ForestClientUserSession.ts
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormSubmittedPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

---
[Backend](https://nr-forest-client-46-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-46-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-46-legacy.apps.silver.devops.gov.bc.ca/) available

fix: Fixes for BCSC and global error

---

frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue
frontend/src/composables/useFetch.ts
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue

---
[Backend](https://nr-forest-client-48-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-48-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-48-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-975: Global message for validation issues not being displayed

---

backend/pom.xml
backend/src/main/java/ca/bc/gov/app/util/ClientValidationUtils.java

---
[Backend](https://nr-forest-client-0-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-0-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-0-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-982: Discrepancy in email validation

---

renovate.json

Pulling from old growth config
---
[Backend](https://nr-forest-client-6-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-6-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-6-legacy.apps.silver.devops.gov.bc.ca/) available

chore: updating renovate config

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/dto/client/ClientBusinessInformationDto.java
backend/src/main/java/ca/bc/gov/app/dto/submissions/SubmissionBusinessDto.java
backend/src/main/java/ca/bc/gov/app/entity/client/SubmissionDetailEntity.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
backend/src/main/java/ca/bc/gov/app/util/ClientMapper.java
backend/src/main/resources/db/migration/V1__initializing_data.sql
backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/utils/ClientSubmissionAggregator.java
backend/src/test/resources/failValidationTest.csv
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/dto/CommonTypesDto.ts
frontend/src/helpers/ForestClientUserSession.ts
frontend/src/pages/FormBCSCPage.vue

---
[Backend](https://nr-forest-client-11-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-11-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-11-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-983: Added DOB in the DB and code

---

frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCSCPage.vue

---
[Backend](https://nr-forest-client-14-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-14-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-14-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-995: Changes for BCSC and some general ones

---

frontend/package-lock.json
frontend/package.json
frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCSCPage.vue

---
[Backend](https://nr-forest-client-18-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-18-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-18-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1000: Move Add Contact button at the bottom when clicking it

---

frontend/src/pages/FormBCSCPage.vue

---
[Backend](https://nr-forest-client-19-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-19-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-19-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1001

---

frontend/src/assets/styles/global.scss

Note: This is an additional PR to [FSADT1-970] (along with #617).
Moves the page content **after** the header, instead of having it **below** the header, **covered** by it.
---
[Backend](https://nr-forest-client-23-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-23-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-23-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-970] Move the page content after the header

---

frontend/src/assets/styles/global.scss
frontend/src/components/MainHeaderComponent.vue

Adjusts menu icon style in the Submissions page, so as to address [comment #6 on [FSADT1-930]](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-930?focusedId=915742&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-915742), which had been forgotten.
---
[Backend](https://nr-forest-client-22-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-22-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-22-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

fix: adjust menu icon style in the Submissions page

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/dto/client/ClientBusinessInformationDto.java
backend/src/main/java/ca/bc/gov/app/entity/client/ClientTypeCodeEntity.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java
backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/utils/ClientSubmissionAggregator.java
backend/src/test/resources/failValidationTest.csv
frontend/src/pages/FormBCeIDPage.vue

---
[Backend](https://nr-forest-client-20-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-20-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-20-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-999: DOB for BCeID for USP and RSP

---

frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCSCPage.vue

---
[Backend](https://nr-forest-client-27-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-27-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-27-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1003: Changes in modal for BCSC

---

backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java

---
[Backend](https://nr-forest-client-36-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-36-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-36-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-999: Changed min age

---

frontend/src/components/forms/DateInputComponent/index.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue

- Displays the birthdate in the review step when it's required;
- Fixes the birthdate regex, which fixes irresponsiveness in the application when the user returned to the business step;
- Fixes a typo;
- Fixes linter issues regarding default values.
Fixes [FSADT1-1019](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1019)
---
[Backend](https://nr-forest-client-48-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-48-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-48-legacy.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

[FSADT1-1019] Display birthdate in the review step

---

frontend/src/components/forms/DateInputComponent/index.vue
frontend/tests/unittests/components/forms/DateInputComponent.spec.ts

Improves validation messages on the Date input component.
Related to [FSADT1-1018](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1018).
---
[Backend](https://nr-forest-client-49-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-49-legacy.apps.silver.devops.gov.bc.ca/) available

feat: improve validation messages on the Date input component

---

frontend/src/components/forms/DateInputComponent/index.vue
frontend/src/helpers/validators/GlobalValidators.ts
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/tests/unittests/pages/bceidform/ContactWizardStep.spec.ts

- Fixes the confirmation message for deleting a contact;
- Also prevents performing a full date validation while the day is invalid.
Fixes [FSADT1-971](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-971)
---
[Backend](https://nr-forest-client-2-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-2-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-2-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-971] Confirmation message for deleting a contact

---

frontend/src/assets/styles/global.scss
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

Fix non-readonly fields label color to be the primary color.
Note: readonly fields were not changed as the design team is still deciding about it.
Fixes [FSADT1-1013](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1013)
---
[Backend](https://nr-forest-client-3-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-3-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-3-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1013] Some field labels are not using the primary color

---

frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/pages/bceidform/AddressWizardStep.vue

- Moves the Country dropdown
- Updates "Add another address" text in step 2
Fixes [FSADT1-1022](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1022)
---
[Backend](https://nr-forest-client-12-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-12-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-12-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1022] Move Country dropdown and update "Add another address" text in step 2

---

frontend/src/helpers/validators/GlobalValidators.ts
frontend/src/pages/FormBCSCPage.vue

---
[Backend](https://nr-forest-client-24-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-24-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-24-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1051: Toast message changes and code reviews

---

frontend/package-lock.json
frontend/package.json
frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/tests/pages/bceid/ContactWizardStep.cy.ts
frontend/tests/unittests/pages/bceidform/ContactWizardStep.spec.ts

---
[Backend](https://nr-forest-client-27-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-27-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-27-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1054: Adjust message for "maximum of 5 additional contacts" use case

---

frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/bceidform/ContactWizardStep.vue

---
[Backend](https://nr-forest-client-30-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-30-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-30-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1054: Deleted word as per requested in a new comment

---

frontend/src/assets/styles/global.scss
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue
frontend/tests/components/components/grouping/ContactGroupComponent.cy.ts

- Addresses issues pointed in the review of FSADT1-1020 (and its subtasks) summarized in [this comment](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1020?focusedId=952477&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-952477);
- Places the birthdate label above its value;
- Restores a previously removed test - "should render the component with validation" - after a small adaptation to it.
Fixes [FSADT1-1020](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1020)
---
[Backend](https://nr-forest-client-28-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-28-frontend.apps.silver.devops.gov.bc.ca/) available …

[FSADT1-1020] Addressing issues pointed in the review

---

frontend/src/pages/FormBCSCPage.vue

Adds one more line of text to modal content.
Fixes [FSADT1-1055](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1055)
---
[Backend](https://nr-forest-client-31-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-31-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-31-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1055] Add text to modal content

---

frontend/src/assets/styles/global.scss

Address comment left in FSADT1-1058.
- Moves toast message below the header (small breakpoint).
Fixes [FSADT1-1058](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1058)
---
[Backend](https://nr-forest-client-34-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-34-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-34-legacy.apps.silver.devops.gov.bc.ca/) available

fix: [FSADT1-1058] BCSC form breakpoints

---

backend/src/main/java/ca/bc/gov/app/filter/CorsWebFilter.java

---
[Backend](https://nr-forest-client-35-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-35-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-35-legacy.apps.silver.devops.gov.bc.ca/) available

fix(FSADT1-1081): Missing "Content-Security-Policy" header

---

frontend/src/components/grouping/ContactGroupComponent.vue

Address comments in Jira ticket.
Fixes [FSADT1-1025](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1025)
---
[Backend](https://nr-forest-client-36-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-36-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-36-legacy.apps.silver.devops.gov.bc.ca/) available

fix: [FSADT1-1025] Update content and fields in step3

---

frontend/tests/components/components/grouping/ContactGroupComponent.cy.ts

---
[Backend](https://nr-forest-client-45-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-45-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-45-legacy.apps.silver.devops.gov.bc.ca/) available

test: try to fix CI issue

---

frontend/tests/unittests/components/forms/DateInputComponent.spec.ts

---
[Backend](https://nr-forest-client-47-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-47-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-47-legacy.apps.silver.devops.gov.bc.ca/) available

test: try to fix issue on Main Merge Workflow

---

frontend/src/assets/styles/global.scss

---
[Backend](https://nr-forest-client-49-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-49-legacy.apps.silver.devops.gov.bc.ca/) available

fix: restrict form steps max-width

---

.github/workflows/merge-main.yml
.github/workflows/unit-tests.yml

---
[Backend](https://nr-forest-client-2-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-2-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-2-legacy.apps.silver.devops.gov.bc.ca/) available

chore: upload cypress screenshots on ci

---

frontend/src/pages/FormBCSCPage.vue

Removes a word in a text line.
Fixes [FSADT1-1089](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1089)
---
[Backend](https://nr-forest-client-5-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-5-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-5-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1089] Delete text

---

frontend/src/components/grouping/ContactGroupComponent.vue

Removes hyperlink from "BCeID" in confirmation message.
Fixes [FSADT1-1090](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1090)
---
[Backend](https://nr-forest-client-6-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-6-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-6-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1090] Remove hyperlink for BCeID in modal

---

frontend/src/assets/styles/global.scss

Reduces the white space around the horizontal divider (before "Business information").
See screenshots with Chrome height adjusted to simulate a scenario/display similar to the one provided in the description of the ticket.
Before (note the blue notification cut off from screen as in the one screenshot in the ticket):
After:
Fixes [FSADT1-1078](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1078)
---
[Backend](https://nr-forest-client-7-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-7-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-7-legacy.apps.silver.devops.gov.bc.ca/) available
Once merged, code will be promoted and …

[FSADT1-1078] Reduce white space

---

frontend/src/pages/FormBCSCPage.vue

Fixes the confirmation message for deleting a contact on BCSC form.
Fixes [FSADT1-971](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-971) (v2 - 15/Dec/23) - This is a different request since the ticket was updated to handle the BCSC form after #652.

[FSADT1-971 v2] BCSC - Confirmation message for deleting a contact

---

frontend/src/assets/styles/global.scss
frontend/src/pages/bceidform/ReviewWizardStep.vue

Aligns review sections to their text titles instead of the icon next to it.
Fixes [FSADT1-1091](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1091)
---
[Backend](https://nr-forest-client-15-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-15-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-15-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1091] Update content alignment in step 4

---

frontend/package-lock.json
frontend/package.json

Fixes issues with UI styles as reported by Ziad: https://teams.microsoft.com/l/message/19:meeting_ZGQ5ZTM2OTgtZTliYi00ZTg0LTg4ZTMtMWY3ZTEwY2FiNDIy@thread.v2/1704734751310?context=%7B%22contextType%22%3A%22chat%22%7D
---
[Backend](https://nr-forest-client-19-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-19-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-19-legacy.apps.silver.devops.gov.bc.ca/) available

fix: downgrade @carbon/web-components back to 2.0

---

processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java

---
[Backend](https://nr-forest-client-21-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-21-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-21-legacy.apps.silver.devops.gov.bc.ca/) available

fix: Fixed null pointer exception

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java

Fixing client type list
---
[Backend](https://nr-forest-client-24-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-24-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-24-legacy.apps.silver.devops.gov.bc.ca/) available

fix: fixing client types

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java

---
[Backend](https://nr-forest-client-25-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-25-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-25-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1119: Related to FSADT1-1038

---

backend/src/main/resources/templates/approval.html

---
[Backend](https://nr-forest-client-27-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-27-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-27-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1116: Right client name in template

---

backend/src/main/java/ca/bc/gov/app/filter/CorsWebFilter.java

---
[Backend](https://nr-forest-client-33-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-33-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-33-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1087: Missing "Referrer policy" Security Header

---

backend/src/main/java/ca/bc/gov/app/filter/CorsWebFilter.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java

---
[Backend](https://nr-forest-client-34-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-34-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-34-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1140: Rejection email fix

---

backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/registration.html

---
[Backend](https://nr-forest-client-42-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-42-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-42-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1146: Change wording and style in emails

---

frontend/src/pages/SubmissionReviewPage.vue

---
[Backend](https://nr-forest-client-41-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-41-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-41-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1135: Removed good standing ind for unregistered clients

---

frontend/package.json

---
[Backend](https://nr-forest-client-45-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-45-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-45-legacy.apps.silver.devops.gov.bc.ca/) available

fix: merge all test coverage results

---

frontend/src/pages/FormBCeIDPage.vue

Fixed NPE by sending information that should be available
---
[Backend](https://nr-forest-client-48-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-48-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-48-legacy.apps.silver.devops.gov.bc.ca/) available

fix(FSADT1-1149): fixing email sent by user

---

.github/workflows/merge-main.yml
backend/src/main/java/ca/bc/gov/app/configuration/ForestClientConfiguration.java
frontend/cypress/support/commands.ts

---
[Backend](https://nr-forest-client-4-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-4-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-4-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1150: Logout URL

---

.github/workflows/pr-open.yml

Minor improvements to PR mod 50 handling to make passing vars easier.
---
[Backend](https://nr-forest-client-5-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-5-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-5-legacy.apps.silver.devops.gov.bc.ca/) available

chore: adjust FOM mod 50 vars

---

backend/src/test/java/ca/bc/gov/app/TestConstants.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java
legacy/src/main/java/ca/bc/gov/app/configuration/ForestClientMetricConfiguration.java
legacy/src/main/java/ca/bc/gov/app/entity/ForestClientEntity.java
legacy/src/main/java/ca/bc/gov/app/entity/ForestClientLocationEntity.java
legacy/src/main/java/ca/bc/gov/app/exception/CannotWriteReportException.java
legacy/src/main/java/ca/bc/gov/app/exception/NoValueFoundException.java
legacy/src/main/java/ca/bc/gov/app/mappers/AbstractForestClientMapper.java
legacy/src/main/java/ca/bc/gov/app/mappers/ForestClientLocationMapper.java
legacy/src/main/java/ca/bc/gov/app/mappers/ForestClientMapper.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientLocationRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientDoingBusinessAsService.java
legacy/src/main/java/ca/bc/gov/app/service/ClientLocationService.java
legacy/src/test/java/ca/bc/gov/app/mappers/ForestClientLocationMapperTest.java

---
[Backend](https://nr-forest-client-6-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-6-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-6-legacy.apps.silver.devops.gov.bc.ca/) available

fix: small fixes

---

frontend/src/components/forms/DropdownInputComponent.vue
frontend/src/components/forms/MultiselectInputComponent.vue
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/helpers/validators/BCeIDFormValidations.ts

Shows an inline error if the user focus the field (either "Primary role" or "Location or address name"), selects nothing and blurs it.
Fixes [FSADT1-1052](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1052)
---
[Backend](https://nr-forest-client-7-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-7-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-7-legacy.apps.silver.devops.gov.bc.ca/) available

fix: validate contact's role and location onblur

---

frontend/src/pages/SubmissionReviewPage.vue

---
[Backend](https://nr-forest-client-9-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-9-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-9-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1150: Fixed bug and improved code

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/tests/pages/bceid/BusinessInformationWizardStep.cy.ts

- Clears error messages when type of business changes;
- Clears error messages when business name gets cleared.
Fixes [FSADT1-1158](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1158) and [FSADT1-1160](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1160)
---
[Backend](https://nr-forest-client-11-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-11-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-11-legacy.apps.silver.devops.gov.bc.ca/) available

[FSADT1-1158] The error message does not get removed when you switch radio selection

---

frontend/package-lock.json
frontend/package.json
frontend/src/main.ts
frontend/src/pages/SubmissionReviewPage.vue

---
[Backend](https://nr-forest-client-12-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-12-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-12-legacy.apps.silver.devops.gov.bc.ca/) available

fix: Hotspot fixes

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientLocationRepository.java

---
[Backend](https://nr-forest-client-14-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-forest-client-14-frontend.apps.silver.devops.gov.bc.ca/) available
[Legacy](https://nr-forest-client-14-legacy.apps.silver.devops.gov.bc.ca/) available

FSADT1-1163: Include the postal code with an AND instead of OR

---

backend/src/main/java/ca/bc/gov/app/controller/client/ClientSubmissionController.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java

fix: fixing pagination

---

backend/src/main/java/ca/bc/gov/app/validator/client/ClientSubmitRequestValidator.java

fix(FSADT1-1143): Display description of the client code in the error messages

---

backend/src/main/java/ca/bc/gov/app/dto/bcregistry/ClientDetailsDto.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java

fix(FSADT1-1179): fixing off ramp cases

---

backend/openshift.deploy.yml
backend/src/main/java/ca/bc/gov/app/configuration/flags/FeatureFlagsConfiguration.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
frontend/README.md
frontend/cypress/e2e/SubmissionReviewPage.cy.ts
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue
frontend/tests/components/components/grouping/ContactGroupComponent.cy.ts
frontend/tests/pages/bceid/AddressWizardStep.cy.ts
frontend/tests/pages/bceid/ContactWizardStep.cy.ts
frontend/tests/unittests/pages/bceidform/ContactWizardStep.spec.ts
frontend/tests/unittests/pages/bceidform/ReviewWizardStep.spec.ts

- Adds a feature flag to control the rendering of component related to multiple addresses, like buttons, fields and on-screen information.
- Auto-associates new contacts to the default address.
Fixes [FSADT1-1171](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1171)
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-31-frontend.apps.silver.devops.gov.bc.ca/)

[FSADT1-1171] Remove additional addresses

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

Associates incoming contacts to the default address in the BCeID form.
---

fix: associate incoming contact to the default address

---

frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue

fix: Fixed small issue in global error msg

---

frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/SubmissionListPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/stub/__files/response-submissions-page0.json
frontend/stub/__files/response-submissions-page1.json
frontend/stub/__files/response-submissions-page2.json
frontend/stub/__files/response-submissions-page3.json
frontend/stub/__files/response-submissions-page4.json
frontend/stub/__files/response-submissions-page5.json
frontend/stub/__files/response-submissions-search.json

- Removes column "Submission type";
- Replaces column "Last updated" with "Submitted on".
Also fixes the "Submitted on" value on the Submission Review page.
Fixes [FSADT1-1182](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1182)

feat(fe:FSADT1-1182): update columns in the submissions table

---

backend/src/main/java/ca/bc/gov/app/dto/client/ClientBusinessInformationDto.java
backend/src/main/java/ca/bc/gov/app/util/ClientMapper.java
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java

fix(be:FSADT1-1172): Fixes related to the district code changes

---

frontend/src/pages/SubmissionReviewPage.vue

feat(fe:FSADT1-1202): UI changes to review client screen

---

frontend/src/pages/FormBCSCPage.vue

feat(fe:FSADT1-1191): Change label to "Mailing address" in BCSC form

---

backend/src/main/resources/db/migration/V1__initializing_data.sql
backend/src/main/resources/templates/revision.html
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java

- Made changes
- Fixed bug related to the size of the subject
---

feat(be:FSADT1-1197): Change to district name instead of Client Admin

---

frontend/src/assets/styles/global.scss
frontend/src/components/MainHeaderComponent.vue
frontend/src/components/UserProfileComponent.vue
frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue

- Renames heading-compact-01 to heading-compact-02 as this corresponds to what we have in the Figma now;
- Creates a new definition for heading-compact-01;
- Applies heading-compact-01 to accordion titles by default;
- Updates the class applied to some elements from heading-compact-01 to heading-compact-02;
- Updates the definition of style body-01;
- Updates the class applied to some elements from body-01 to body-02;
- Applies body-01 to some items' title.
Fixes [FSADT1-1193](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1193)
---
[Main Merge …

feat(fe:FSADT1-1193): fix heading styles and color

---

frontend/src/pages/SubmissionReviewPage.vue

Moves the "Submitted on" output field to the "Client summary" section.
Fixes [FSADT1-1192](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1192)
---

feat(fe:FSADT1-1192): move "Submitted on" output field

---

backend/src/main/java/ca/bc/gov/app/job/ches/ChesEmailResendJob.java
backend/src/main/java/ca/bc/gov/app/service/ches/ChesService.java
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java

fix(FSADT1-1199): fixing email for district

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java

- Made a small change in the email content
- Removed unused code
- Gave format to the code
---

feat(be:FSADT1-1198): Change in the email content

---

frontend/src/pages/SubmissionReviewPage.vue

feat(fe:FSADT1-1169): Adjust notification message

---

frontend/src/pages/SubmissionReviewPage.vue

fix(fe:FSADT1-1169): Fix to deal with grammar when plural

---

.github/workflows/unit-tests.yml
frontend/package.json
frontend/src/routes.ts

- fixed an issue when user is not logged in and not redirect.
- now user can redirect to page he was trying to see
---

fix(FSADT1-1165): fixing user redirect

---

frontend/src/pages/SubmissionReviewPage.vue

fix(fe:FSADT1-1207): Link is not working properly (per client number)

---

frontend/src/pages/FormSubmittedPage.vue

Skip decorative image for accessibility since it's decorative and ["already sufficiently described by the adjacent text"](https://www.w3.org/WAI/tutorials/images/decorative/#example-3-image-with-adjacent-text-alternative): "Application submitted!".
---

feat(fe:FSADT1-1006): skip decorative image for accessibility

---

frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue

fix(FSADT1-1233): fixing address issue

---

frontend/src/pages/FormBCeIDPage.vue

Prevents progress steps to be treated as buttons by fixing their tabindex and role.
---

fix(fe:FSADT1-1006): skip progress steps from tab navigation

---

frontend/src/App.vue

Enables the screen reader to detect the updated content on router-view and read it out.
For example: when reaching the application submitted page.

feat(fe:FSADT1-1006): read application submitted message

---

frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/LandingPage.vue

feat(fe:FSADT1-1232): Fixed distance between buttons

---

frontend/cypress/e2e/FormBCSCPage.cy.ts
frontend/cypress/e2e/SubmissionReviewPage.cy.ts
frontend/src/assets/styles/global.scss
frontend/src/components/MainHeaderComponent.vue
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormSubmittedPage.vue
frontend/src/pages/SubmissionListPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue
frontend/tests/unittests/pages/bceidform/ReviewWizardStep.spec.ts

Orders the heading tags so that the first heading in a page is an h1, and no tag level is skipped.
For example: there should be no h3 if the previous used heading is an h1. In such case we either forgot to add an h2 or we should turn this h3 into an h2.
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-38-frontend.apps.silver.devops.gov.bc.ca/)

feat(fe:FSADT1-1006): follow the expected heading order

---

.github/workflows/merge-main.yml
.github/workflows/pr-open.yml

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-39-frontend.apps.silver.devops.gov.bc.ca/)

fix: fixing deploy config

---

.github/workflows/merge-main.yml

ci: fixing logout url

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/components/forms/DropdownInputComponent.vue
frontend/src/components/forms/MultiselectInputComponent.vue
frontend/src/components/forms/RadioInputComponent.vue

Fixes reactivity on a11y attributes.
i.e. the a11y attributes must be updated whenever the props they depend on get updated.
---

fix(fe:FSADT1-1006): fix reactivity on a11y attributes

---

database/openshift.backup.yml

ci: exclude district code table

---

.github/workflows/pr-validate.yml

fix(ci): pr-validate version

---

.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml
backend/openshift.deploy.yml
common/openshift.init.yml
frontend/openshift.deploy.yml
legacy/openshift.deploy.yml
processor/openshift.deploy.yml

Replaces https://github.com/bcgov/nr-forest-client/pull/855.
---

chore(ci): prep routes and templates for vanity urls

---

frontend/cypress/e2e/FormBCSCPage.cy.ts
frontend/cypress/e2e/FormGeneral.cy.ts
frontend/cypress/e2e/SubmissionReviewPage.cy.ts
frontend/src/components/MainHeaderComponent.vue
frontend/src/pages/LandingPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/tests/unittests/components/MainHeaderComponent.spec.ts

feat(fe): Changed name of the application

---

.github/workflows/merge.yml

chore(ci): load new routes

---

frontend/package-lock.json
frontend/package.json

- https://github.com/bcgov/nr-forest-client/security/code-scanning/155
- https://github.com/bcgov/nr-forest-client/security/dependabot/33
---

chore(deps): override follow-directs subdep for vulerability

---

backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/matched.html
backend/src/main/resources/templates/registration.html
backend/src/main/resources/templates/rejection.html
backend/src/main/resources/templates/revision.html

feat(be): Changed app name

---

frontend/src/components/forms/DateInputComponent/index.vue

Prevents horizontal scroll due to date field inputs.
---

feat(fe:FSADT1-1006): prevent horizontal scroll due to date field inputs

---

frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormSubmittedPage.vue

Sets roles to some screen regions: form and main.
[1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships)
---

feat(fe:FSADT1-1006): set roles form and main

---

frontend/package-lock.json
frontend/package.json
frontend/src/CoreConstants.ts
frontend/src/helpers/ForestClientUserSession.ts
frontend/stub/mappings/fam.json

fix(FSADT1-1212): fixing stubs

---

frontend/src/App.vue
frontend/src/pages/FormSubmittedPage.vue

Adds a main role around the form role, so to make sure user can easily skip to the main section in the form pages.
See: [2.4.1 Bypass Blocks](https://www.w3.org/TR/WCAG22/#bypass-blocks)
The one in the form submitted page was removed to prevent duplication of the role.
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-31-frontend.apps.silver.devops.gov.bc.ca/)
- [Merge …

feat(fe:FSADT1-1006): set main role on the form pages

---

frontend/index.html
frontend/package.json

feat(fe): Changed app name in title

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/converters/GrantedAuthoritiesConverter.java
backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java

Updating code to read the FAM roles
---

feat(FSADT1-1238): updating code to read FAM roles

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/stub/mappings/backend.json

fix(FSADT1-1224): fixing individual check on bceid

---

.github/workflows/merge.yml
.github/workflows/reusable-tests-fe.yml
.github/workflows/scheduled.yml
backend/pom.xml
legacy/pom.xml
processor/pom.xml

fixing some CVEs and updating some parameters
---

fix(CVE-2024-22259|CVE-2023-52428): CVE fixes

---

backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/revision.html

fix(be:FSADT1-1260): Updated wording in email templates

---

backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-40-frontend.apps.silver.devops.gov.bc.ca/)

fix(FSADT1-1268): fix access to details api

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/configuration/SecurityConfiguration.java
backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java
backend/src/test/java/ca/bc/gov/app/controller/ches/ChesControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientAddressControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientCodesControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientCountryControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientDistrictControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java
frontend/src/helpers/ForestClientUserSession.ts
frontend/src/pages/SubmissionReviewPage.vue

fix(FSADT1-1267): prevented warning rbac in case of error rbac

---

frontend/src/App.vue
frontend/src/assets/styles/global.scss
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/composables/useFocus.ts
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormSubmittedPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/src/pages/bceidform/ReviewWizardStep.vue
frontend/tests/pages/bceid/AddressWizardStep.cy.ts

- adds a status message about the current step;
- updates roles so the main section is the part that contains the current step UI;
- removes focus on step's first input field; focus its heading instead.
Also fixes the business name label.
---
- [Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/work …

feat(fe:FSADT1-1006): add progress status message

---

.github/workflows/merge.yml

feat: Update GitHub Actions workflow to use read only account for the oracle DB.

---

.github/workflows/merge.yml

fix: Removed wrong parameters

---

.github/workflows/merge.yml

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-48-frontend.apps.silver.devops.gov.bc.ca/)

fix: fixing prod deployment config

---

frontend/src/helpers/ForestClientUserSession.ts

Updated the token refresh time to be 90% of the expiration. This will allow the token to refresh before it expires. The time is based on the received expiration time from the token
---

fix(FSADT1-1276): token refresh time is 90% of exp

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
backend/src/main/java/ca/bc/gov/app/service/ches/ChesService.java
backend/src/test/java/ca/bc/gov/app/controller/ches/ChesControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/service/ches/ChesServiceIntegrationTest.java

chore: adjusting the ches configuration

---

backend/openshift.deploy.yml

chore(be): updating annotations

---

frontend/src/pages/FormBCSCPage.vue

fix(fe): Fixed bug related to DOB

---

backend/pom.xml
backend/src/main/java/ca/bc/gov/app/health/BcRegistryApiHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/health/CanadaPostApiHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/health/ChesHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/job/ches/ChesEmailResendJob.java
backend/src/main/java/ca/bc/gov/app/service/bcregistry/BcRegistryService.java
backend/src/main/java/ca/bc/gov/app/service/ches/ChesService.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientAddressService.java

fix: mail sent and mail status

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/tests/pages/bceid/BusinessInformationWizardStep.cy.ts

Makes sure the individual only gets successfully validated when response status code is either 200 or 404.
Fixes [FSADT1-1292](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1292)
---

fix(fe:FSADT1-1292): validate individual

---

frontend/src/components/MainHeaderComponent.vue

feat(fe): Changed btn title for consistency

---

frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/stub/__files/response-address-G1V2W5.json
frontend/stub/__files/response-address-search-CA.json

Validates autocomplete's selected value immediately.
---

fix(fe): validate autocomplete's selected value immediately

---

.github/workflows/reusable-tests-fe.yml

chore(ci): update js tester action

---

backend/src/main/java/ca/bc/gov/app/util/ClientValidationUtils.java
backend/src/main/java/ca/bc/gov/app/validator/client/ClientContactDtoValidator.java

feat(be:FSADT1-1277): BE validations

---

frontend/src/pages/LandingPage.vue
frontend/src/pages/LogoutPage.vue

- Fixed grammar error
- Improved logout page
- Beautified code
---

feat(fe): Small improvements

---

frontend/src/helpers/validators/SubmissionReviewValidations.ts
frontend/src/pages/SubmissionReviewPage.vue

Validates fields Reason for rejection and Matching client number when rejecting a submission.
- Prevents characters other numbers on the Matching client number;
- Limits to 8 character;
- Displays inline error messages.
---

feat(fe): add validations to reject submission fields

---

.github/workflows/merge.yml

feat: Update workflow to use read-write account for the oracle DB in Prod

---

processor/src/main/java/ca/bc/gov/app/matchers/LegalNameProcessorMatcher.java

Updating fuzzy match to be executed on every kind of submission
---

fix(FSADT1-1312): making fuzzy works for all types

---

frontend/src/App.vue
frontend/src/components/MainHeaderComponent.vue
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/AddressWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/src/services/ForestClientService.ts
frontend/tests/unittests/services/ForestClientService.spec.ts

Announce dialogs properly with screen readers.
- Inform its title;
- Inform its description;
- Give more context on button labels - both the button to open the dialog and the one to confirm its action.
Fixes [FSADT1-1295](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1295)
---

feat(fe:FSADT1-1295): announce dialogs properly

---

frontend/src/components/DataFetcher.vue
frontend/src/components/grouping/AddressGroupComponent.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/stub/mappings/backend.json
frontend/tests/unittests/components/DataFetcher.spec.ts

Disables the data-fetcher on Business name and the one on Street address when the url is missing the search parameter.
Also updates the related backend stubs so we could see the same errors we were seeing when using the real back-end.
Fixes [FSADT1-1299](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1299)
---
- [Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/workflow …

fix(fe:FSADT1-1299): disable data-fetcher when url is not complete

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
backend/openshift.deploy.yml
backend/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
backend/src/main/java/ca/bc/gov/app/health/BcRegistryApiHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/health/CanadaPostApiHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/health/ChesHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/health/HealthExchangeFilterFunction.java
backend/src/main/java/ca/bc/gov/app/health/LegacyApiHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/health/ManualHealthIndicator.java
backend/src/main/java/ca/bc/gov/app/job/ches/ChesEmailResendJob.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientLegacyService.java
backend/src/main/resources/application.yml
backend/src/test/java/ca/bc/gov/app/controller/ches/ChesControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientControllerIntegrationTest.java

As per the request from the BC Registry team, specifically Patrick Wei from CITZ, we need to revise our approach to health checks for the BC Registry API. The BC Registry API runs on Google Cloud and is billed based on requests, and it does not provide a dedicated health check endpoint.
To accommodate this requirement, we need to adjust our health check mechanism to monitor the status of responses from the BC Registry API. This will involve tracking the status of API responses and updating our health check process accordingly.
---
Please create PRs in draft mode. …

fix(FSADT1-1314): Update Health Check Mechanism for BC Registry API Integration

---

processor/src/main/java/ca/bc/gov/app/ProcessorApplication.java
processor/src/main/java/ca/bc/gov/app/configuration/SchedulerConfiguration.java
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java
processor/src/main/java/ca/bc/gov/app/service/processor/ProcessorService.java
processor/src/test/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingServiceIntegrationTest.java
processor/src/test/resources/application-default.yml
processor/src/test/resources/db/migration/R__test._data.sql

Application was receiving review email when it should not.
---

fix(FSADT1-1321): Applicant should not be copied in the Review email

---

frontend/src/assets/styles/global.scss
frontend/src/components/MainHeaderComponent.vue
frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue
frontend/src/pages/SubmissionListPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/services/ForestClientService.ts
frontend/tests/pages/bceid/BusinessInformationWizardStep.cy.ts

feat(fe:FSADT1-1107): Add text and obfuscated emails

---

backend/src/main/java/ca/bc/gov/app/job/ches/ChesEmailResendJob.java

chore: removing noise from logs

---

backend/pom.xml
backend/src/test/java/ca/bc/gov/app/util/PkceUtilTest.java
legacy/pom.xml
processor/pom.xml

Updating dependency to fix and close #899
Netty is an asynchronous event-driven network application framework for the rapid development of maintainable high-performance protocol servers & clients. The "HttpPostRequestDecoder" can be tricked to accumulate data. While the decoder can store items on the disk if configured so, there are no limits to the number of fields the form can have, an attacker can send a chunked post consisting of many small fields that will be accumulated in the "bodyListHttpData" list. The decoder cumulates bytes in the `undecodedChunk` buffer until it can decode a field, this field can cumulate data without limits. This issue affects versions through 4.1.107.Final, and 5.0.0.Alpha1 through 5.0.0.Alpha2.
---
Deployments, as required, will be …

fix(sec:CVE-2024-29025): Allocation of Resources Without Limits or Throttling

---

backend/docs/cve-ignore.xml
backend/pom.xml
legacy/docs/cve-ignore.xml
legacy/pom.xml
processor/docs/cve-ignore.xml
processor/pom.xml

In Connect2id Nimbus JOSE+JWT versions 4.0-rc1 through 9.37.1, an attacker can cause a Denial of Service (through Uncontrolled Resource Consumption) via a large JWE p2c header value (aka iteration count) for the 'PasswordBasedDecrypter' (PBKDF2) component.
Updating dependency to fix and close #885
--- …

fix(sec:CVE-2023-52428): DoS in Connect2id Nimbus JOSE+JWT

---

frontend/src/pages/SubmissionReviewPage.vue
frontend/tsconfig.json

feat(fe:FSADT1-1227): Matching links goes straight to the tab

---

processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyLoadingService.java

fix(FSADT1-1332): fixing matcher for processor

---

backend/src/main/resources/db/migration/V4__district_email_update.sql

As requested, I am updating DKM district email address
---

fix(FSADT1-1338): updated district dkm email

---

backend/src/main/resources/db/migration/V5__district_email_update.sql

fix(FSADT1-1341): updated district dos email

---

processor/pom.xml

chore: updating deps

---

frontend/package-lock.json
frontend/package.json

fix: Correct start-server-and-test Command in preview Script

---

backend/openshift.deploy.yml
legacy/openshift.deploy.yml

After some investigation and some help from the platform team, it was determined that the reason behind pods restarting and some other failures is out of memory. We are increasing the resource quota for some of our services to prevent this kind of event.
---

fix(FSADT1-1372): increasing memory due to OOM

---

backend/src/main/java/ca/bc/gov/app/models/client/SubmissionTypeCodeEnum.java
backend/src/main/resources/db/migration/V7__staff_submitted_data.sql
backend/src/main/resources/db/migration/V8__fcms_v2_changes.sql
backend/src/test/java/ca/bc/gov/app/controller/client/ClientSubmissionControllerIntegrationTest.java
backend/src/test/resources/db/migration/R__Test_Data.sql

added the new type along with the new enum
adding staff submitted data type and enum to allow staff submitted data to be handled.
---
---
Any successful deployments (not always required) will be available …

feat(FSADT1-1362): staff created entries

---

legacy/src/main/java/ca/bc/gov/app/service/ClientService.java

fix: deleted unneeded code

---

backend/src/main/resources/db/migration/V9__district_email_update.sql

feat(be:FSADT1-1393): Updated DCS district email

---

backend/src/main/java/ca/bc/gov/app/dto/submissions/SubmissionDetailsDto.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/SubmissionReviewPage.vue

feat(FSADT1-1342): Display why and who rejected a submission

---

backend/src/main/java/ca/bc/gov/app/dto/client/ClientContactDto.java
backend/src/main/java/ca/bc/gov/app/dto/legacy/ContactSearchDto.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientLegacyService.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientMatchService.java
backend/src/main/java/ca/bc/gov/app/service/client/matches/ContactStepMatcher.java
backend/src/main/java/ca/bc/gov/app/service/client/matches/LocationStepMatcher.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientMatchLocationControllerIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/extensions/ClientMatchDataGenerator.java
backend/src/test/java/ca/bc/gov/app/service/client/ClientMatchServiceIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/service/client/matches/ContactStepMatcherTest.java
backend/src/test/java/ca/bc/gov/app/service/client/matches/IndividualStepMatcherTest.java
legacy/src/main/java/ca/bc/gov/app/controller/ClientSearchController.java
legacy/src/main/java/ca/bc/gov/app/dto/ContactSearchDto.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientContactRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientContactService.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java
legacy/src/test/java/ca/bc/gov/app/service/ClientSearchServiceIntegrationTest.java

When a contact is added to the staff screen, a fuzzy match should be triggered to check if the contact already exists in the system. The fuzzy match for contact should be grouped into distinct groups, that will be then checked against the existing entries. In case of a match, the fuzzy match should return the data pointing out to what entry it matches, so it can be shown for each contact entry. One match block should be the combination of first name, last name, email and any phone number, the second one should be each phone number and the last one should be the email address.
--- …

feat(FSADT1-1364): backend fuzzy match for contacts

---

frontend/src/pages/SubmissionListPage.vue

- Added missing line that was not in Figma
---

feat(fe:FSADT1-1382): Added code for the dashboard empty state

---

backend/src/main/java/ca/bc/gov/app/ApplicationConstant.java
backend/src/main/java/ca/bc/gov/app/controller/client/ClientController.java
backend/src/main/java/ca/bc/gov/app/controller/filters/UserIdWebFilter.java
backend/src/main/java/ca/bc/gov/app/util/JwtPrincipalUtil.java
backend/src/main/resources/application.yml

added the userid to the log as a way to track user interaction 
---

feat: added user identification to logs

---

frontend/src/pages/SubmissionListPage.vue

Fixed an issue where the empty state of the data list was showing even when data list was loading
---

fix(FSADT1-1382): limited empty state to loaded

---

frontend/src/helpers/validators/BCeIDFormValidations.ts

fix(fe): Aligned FE validation with BE validation as per agreement

---

frontend/src/components/grouping/StaffContactGroupComponent.vue
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/helpers/validators/StaffFormValidations.ts
frontend/src/pages/FormStaffPage.vue

feat(FSADT1-1347): create client for staff Step 3 - Contacts

---

frontend/cypress/e2e/FormStaffPage.cy.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/grouping/StaffLocationGroupComponent.vue
frontend/src/helpers/validators/StaffFormValidations.ts
frontend/src/pages/FormStaffPage.vue
frontend/src/pages/staffform/ReviewWizardStep.vue
frontend/tests/pages/staff/ContactWizardStep.cy.ts

feat(fe:FSADT1-1350): Create client for staff Step 4 - Review

---

frontend/cypress/e2e/FormStaffPage.cy.ts
frontend/src/CoreConstants.ts
frontend/src/components/MainHeaderComponent.vue
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/FormStaffConfirmationPage.vue
frontend/src/pages/FormStaffPage.vue
frontend/src/routes.ts
frontend/tests/unittests/components/MainHeaderComponent.spec.ts

feat(fe:FSADT1-1385): Create the "Client created" page for staff

---

frontend/src/helpers/validators/StaffFormValidations.ts
frontend/src/pages/FormStaffPage.vue
frontend/src/pages/staffform/IndividualClientInformationWizardStep.vue
frontend/tests/unittests/helpers/validators/StaffFormValidations.spec.ts

feat(fe:FSADT1-1389): Create client for staff - no selection

---

frontend/src/components/forms/TextInputComponent.vue
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/helpers/validators/StaffFormValidations.ts
frontend/src/pages/staffform/IndividualClientInformationWizardStep.vue
frontend/tests/unittests/helpers/validators/StaffFormValidations.spec.ts

feat(fe:FSADT1-1402): Create client for staff Step 1 - Individuals - capturing other ID
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/)

feat(fe:FSADT1-1402): Create client for staff Step 1 - Individuals - capturing other ID

---

frontend/src/components/MainHeaderComponent.vue

fix(fe:FSADT1-1414): Left menu active status

---

frontend/src/components/grouping/StaffContactGroupComponent.vue
frontend/src/pages/FormStaffPage.vue

Prevents from moving to the next step when a required field is empty.
Also updates messages about the need to fill out 'all required fields' - instead of saying 'all fields'.
Fixes [FSADT1-1347](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1347)
---
---
Deployments, as …

fix: staff contact validation

---

processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyIndividualPersistenceService.java
processor/src/main/java/ca/bc/gov/app/util/ProcessorUtil.java
processor/src/test/java/ca/bc/gov/app/service/legacy/LegacyIndividualPersistenceServiceTest.java

Fixed the missing middle name parameter while adding some more test cases
---

fix(FSADT1-1422): added the missing middle name

---

backend/src/main/java/ca/bc/gov/app/util/ClientMapper.java

External users provided empty fields for some staff-related data, and this was causing some constraint issues.
---

fix(FSADT1-1425): fixed mapping issues for external

---

frontend/src/pages/FormStaffPage.vue

removed the fuzzy match call as it was failing
---

fix: removing fuzzy match

---

legacy/src/main/java/ca/bc/gov/app/service/ClientService.java
processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingService.java
processor/src/test/java/ca/bc/gov/app/service/client/ClientSubmissionLoadingServiceIntegrationTest.java

The process completes successfully when a submission is processed and approved, but the final email containing the client number is not sent to the user.
---

fix(FSADT1-1428): fixed email not beint sent

---

frontend/src/pages/FormStaffPage.vue

fix(fe): Commenting this for now until the API for fuzzy match is done
---

fix(fe): Commenting this for now until the API for fuzzy match is done

---

frontend/src/pages/FormStaffPage.vue

removed validation that caused issues. It wasn't 100% necessary for the staff case
---

chore: removing validation

---

backend/src/main/resources/application.yml

Added missing headers that are preventing the matcher due to CORS
---

fix(FSADT1-1363): added missing headers for cors

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

in case of bc registry data with multiple addresses, we order to have the mailing first, and we remove any other location on the frontend
---

fix(FSADT1-1426): fixed multi-address issue

---

backend/openshift.configmap.prod.yml
backend/openshift.configmap.test.yml
backend/src/main/java/ca/bc/gov/app/configuration/flags/FeatureFlagsConfiguration.java

fix: fixing feature flag

---

backend/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
backend/src/main/java/ca/bc/gov/app/util/ClientMapper.java
backend/src/main/resources/application.yml
legacy/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java

Fixing native dtos that were not flagged
---

fix: fixing missing dto for native reflection

---

backend/src/main/java/ca/bc/gov/app/dto/client/ClientTypeEnum.java
backend/src/main/java/ca/bc/gov/app/service/opendata/AbstractOpenDataService.java
frontend/cypress/e2e/FormGeneral.cy.ts
frontend/cypress/e2e/FormStaffPageSubmission.cy.ts
frontend/tests/components/pages/staffform/BcRegisteredClientInformationWizardStep.cy.ts

fix(fe): Added missing client types and made code reviews

---

backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java

Added missing security role that allowed the processor service to call the backend
---

fix(FSADT1-1431): added security role for districts

---

frontend/package.json
frontend/src/components/MainHeaderComponent.vue
frontend/src/components/grouping/ContactGroupComponent.vue
frontend/src/pages/FormStaffPage.vue
frontend/tests/unittests/pages/FormStaffPage.spec.ts

Changed the order of entries for the client type dropdown that appears in the staff page
---

fix(FSADT1-1415): reordering the client type for staff

---

processor/src/main/java/ca/bc/gov/app/entity/SubmissionLocationEntity.java

fix(be:FSADT1-1446): Wrong main address being persisted in Oracle

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientService.java

fix(be:FSADT1-1449): Fixed order of business search by name

---

frontend/src/pages/staffform/FirstNationClientInformationWizardStep.vue

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-38-frontend.apps.silver.devops.gov.bc.ca/)

fix(fe:FSADT1-1390): Changed label as per requested

---

frontend/src/assets/styles/global.scss
frontend/src/pages/FormStaffConfirmationPage.vue
frontend/src/pages/FormStaffProcessingPage.vue
frontend/src/routes.ts
frontend/stub/mappings/fuzzy_matches.json

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-39-frontend.apps.silver.devops.gov.bc.ca/)

fix(FSADT1-1442): fixed staff submission completion menu

---

frontend/cypress/e2e/FormStaffPageFuzzy.cy.ts
frontend/cypress/e2e/FormStaffPageSubmission.cy.ts
frontend/cypress/fixtures/fuzzy/full_address_business_phone_match.json
frontend/cypress/fixtures/fuzzy/full_address_email_match.json
frontend/cypress/fixtures/fuzzy/full_address_fax_phone_match.json
frontend/cypress/fixtures/fuzzy/full_address_match.json
frontend/cypress/fixtures/fuzzy/full_address_secondary_phone_match.json
frontend/cypress/fixtures/testdata/locationBaseData.json
frontend/cypress/support/commands.ts
frontend/cypress/support/cypress.d.ts
frontend/package-lock.json
frontend/package.json
frontend/src/assets/styles/global.scss
frontend/src/components/grouping/FuzzyMatchNotificationGroupingComponent.vue
frontend/src/dto/CommonTypesDto.ts
frontend/src/helpers/validators/GlobalValidators.ts
frontend/src/pages/FormStaffPage.vue
frontend/src/pages/staffform/LocationsWizardStep.vue
frontend/stub/__files/fuzzy/full_address_1_match.json
frontend/stub/__files/fuzzy/full_address_match.json
frontend/stub/mappings/fuzzy_matches.json
frontend/tests/components/pages/staffform/LocationsWizardStep.cy.ts
frontend/tests/unittests/components/grouping/FuzzyMatchNotificationGroupingComponent.spec.ts

Adds per-location fuzzy matching notifications, expands the ones with errors and collapse the ones with no error, and scrolls to the first error notification.
And also:
- adds the partialMatch property to control the kind of text to be presented on the group of fields;
- fixes values associated with locations, like the location name in the accordion item title, specially when a location that is not the last one gets deleted - the error would be in the ones after it.
Fixes [FSADT1-1357](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1357)
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-40-frontend.apps.silver.devops.gov.bc.ca/)
Please create PRs in draft mode. …

feat(fe: FSADT1-1357): Create client for staff - Frontend Fuzzy matching on Locations

---

frontend/src/pages/staffform/ReviewWizardStep.vue

fix(fe:FSADT1-1440|FSADT1-1441): Made changes in Staff Review Page as per requested

---

legacy/Dockerfile
legacy/src/main/java/ca/bc/gov/app/entity/ForestClientLocationEntity.java

fix(FSADT1-1465): submission stuck due to data inconsistency

---

frontend/package-lock.json
frontend/package.json

chore: updated carbon styles

---

frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue
frontend/src/pages/staffform/ReviewWizardStep.vue

fix(fe:FSADT1-1461): Missing Business Type for B.C. Registered business

---

frontend/cypress/e2e/FormStaffPage.cy.ts
frontend/src/assets/styles/global.scss
frontend/src/components/grouping/StaffContactGroupComponent.vue

Fixes the error notification that was not visible in Safari.
And also: 
- fixes contact validations that were just not running - because were not loaded correctly;
- removes a .only found in a Cypress test file;
- fixes a Cypress test.
---

fix: fix notification visibility on Safari and other fixes

---

backend/src/main/java/ca/bc/gov/app/service/opendata/OpenDataService.java

fix(be:FSADT1-1478): Order issue with First Nation names

---

frontend/cypress/e2e/pages/staffform/BcRegisteredClientInformationWizardStep.cy.ts
frontend/src/pages/FormStaffPage.vue
frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

Resets the information in the form when any of the following inputs changes:
- Business name;
- Client type.
Fixes [FSADT1-1467](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1467)
---

fix(fe: FSADT1-1467): resets the form when the business name changes

---

backend/src/main/java/ca/bc/gov/app/service/client/matches/LocationStepMatcher.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientLocationRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java

fix(FSADT1-1477): fixed location matcher

---

backend/pom.xml
backend/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java

Prevented the first email in case of staff submission
---

fix(FSADT1-1464): preventing the first email for staff

---

frontend/src/assets/styles/global.scss

Adds a margin-left to prevent cutting the badge pictogram on the staff confirmation page.
Fixes [FSADT1-1463](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1463)
---

fix(fe: FSADT1-1463): add margin to prevent pictogram cut

---

frontend/src/pages/staffform/FirstNationClientInformationWizardStep.vue
frontend/src/pages/staffform/IndividualClientInformationWizardStep.vue

Turns autocomplete attribute off for staff, since data is not about the staff user themself.
---

fix(fe): turn autocomplete attribute off

---

frontend/package-lock.json
frontend/package.json

chore: Upgraded carbon styles

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-38-frontend.apps.silver.devops.gov.bc.ca/)

fix(fe:FSADT1-1490): Issue when trying to save an unregistered client with BCeID

---

frontend/cypress/e2e/pages/FormStaffPageFuzzy.cy.ts
frontend/cypress/support/commands.ts
frontend/cypress/support/cypress.d.ts
frontend/src/pages/FormStaffPage.vue

Skips validation check when the review statement is checked.
And adds many tests to prevent the same error from occurring again.
Fixes [FSADT1-1491](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1491)
---

fix(fe: FSADT1-1491): Fuzzy matching scenario does not allow user to proceed to next step

---

frontend/src/pages/SubmissionReviewPage.vue

feat(fe:FSADT1-1432): Change message to staff submission form users

---

backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/revision.html

feat(be:FSADT1-1433): Review email signatures for consistency

---

frontend/src/assets/styles/global.scss
frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

feat(fe:FSADT1-1493): Change exclamation mark color

---

frontend/src/assets/styles/global.scss

Ensure that the BC Sans font applies to all text elements across the entire application
---

fix(fe:FSADT1-1492): Ensure that the BC Sans font applies to all texts

---

frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

fix(fe:FSADT1-1494): Removed icon

---

frontend/Caddyfile
frontend/Dockerfile

Updated cache to prevent stale data. 
- max-age=1800: Cache for 30 minutes in the browser.
- s-maxage=1800: Cache for 30 minutes in shared caches like CDNs.
- stale-while-revalidate=600: If stale, the resource can still be served while it’s revalidated in the background for up to 5 minutes.
- stale-if-error=3600: Serve stale content for up to 1 hour if an error occurs.
---
- [Merge …

fix(FSADT1-1498): updating cache

---

frontend/src/pages/staffform/ReviewWizardStep.vue
frontend/src/services/ForestClientService.ts

fix(fe:FSADT1-1505): Location notes in the Review step missing break lines

---

backend/pom.xml
frontend/src/pages/staffform/ReviewWizardStep.vue
frontend/src/services/ForestClientService.ts

chore: last merge before code freeze

---

frontend/src/assets/styles/global.scss
frontend/src/components/MainHeaderComponent.vue

feat(fe:FSADT1-1503): Adjust button and message for the "Need help?" side menu item

---

frontend/src/components/MainHeaderComponent.vue

feat(fe:FSADT1-1445): Change "Logout" icon in "My profile" panel

---

frontend/src/components/MainHeaderComponent.vue

feat(fe:FSADT1-1502): Adjust logout behavior

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

feat(FSADT1-779): adding cypress scenarios (#1139)

---

backend/pom.xml
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
legacy/pom.xml
processor/pom.xml
processor/src/main/java/ca/bc/gov/app/ApplicationConstant.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyRegisteredSPPersistenceService.java
processor/src/test/java/ca/bc/gov/app/service/legacy/LegacyRegisteredSPPersistenceServiceTest.java

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-31-frontend.apps.silver.devops.gov.bc.ca/)

chore: merge main into client2 to solve conflicts

---

.github/workflows/analysis.yml
.github/workflows/issue-gherkin.yml
.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml
.github/workflows/reusable-doc-gen.yml
.github/workflows/reusable-tests-be.yml
.github/workflows/reusable-tests-fe.yml
.github/workflows/reusable-tests-repo.yml
.github/workflows/scheduled.yml

Updating workflows to use `ubuntu-24.04` and adding openshift cli install action due to the missing openshift client on 24.04
---

ci(deps): updating deployer and workflows

---

frontend/src/components/forms/DateInputComponent/index.vue

Fixes the revalidation on the DateInputComponent, specially when triggered by an edit on its own value, by stopping the validation in case any of the date parts are found to be invalid, instead of proceeding to the full date validation.
Fixes [FSADT1-1488](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1488)
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-38-frontend.apps.silver.devops.gov.bc.ca/)
- [Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/workfl …

fix(fe: FSADT1-1488): revalidate the date value properly

---

frontend/package-lock.json
frontend/package.json

chore: upgrade vue

---

frontend/src/components/forms/DateInputComponent/index.vue
frontend/tests/unittests/components/forms/DateInputComponent.spec.ts

Fixes the validation on the DateInputComponent for pasted or autocomplete-selected values.
Fixes [FSADT1-1421](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1421)
---

fix(fe: FSADT1-1421): fix date validation for pasted/autocompleted values

---

frontend/package-lock.json
frontend/package.json

chore: upgrade types node

---

frontend/src/components/forms/DateInputComponent/index.vue

Prevents running the full date validation when there is an error in a part of the date on its own, by initializing the date properly.
---
---
Any successful deployments (not always required) will be available …

fix(fe): stop date validation when part of it has an error

---

frontend/package-lock.json
frontend/package.json

chore: upgrade vue and cypress coverage

---

frontend/src/components/MainHeaderComponent.vue

fix(fe:FSADT1-1503): Changed help modal title

---

legacy/src/main/java/ca/bc/gov/app/dto/PredictiveSearchResultDto.java

feat(fe:FSADT1-1524): renamed variable for consistency (similar to clientType)

---

backend/src/main/java/ca/bc/gov/app/dto/client/LegalTypeEnum.java
backend/src/main/java/ca/bc/gov/app/util/ClientValidationUtils.java
backend/src/test/java/ca/bc/gov/app/utils/ClientValidationUtilsTest.java

Added missing relationship between LL (Limited Liability) to Limited Partnership
---

fix(FSADT1-1537): adding missing relation to LL

---

frontend/src/components/MainHeaderComponent.vue

fix(fe:FSADT1-1503): Put title as it was before

---

frontend/src/helpers/DataConverters.ts

fix(fe:FSADT1-1537): adding missing relation to LL

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java

fix(be:FSADT1-1528): fixed column alias

---

processor/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionProcessingService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyRegisteredSPPersistenceService.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyService.java

fix(FSADT1-1536): more fixes

---

frontend/package-lock.json
frontend/package.json

chore(fe): Upgraded vue

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded aws-amplify

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded icons-vue

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded types/node

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded vitejs/plugin-vue

---

frontend/package-lock.json
frontend/package.json

chore(de): upgraded eslint-plugin-import

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded cypress

---

frontend/src/components/grouping/ErrorNotificationGroupingComponent.vue
frontend/src/pages/SearchPage.vue
frontend/src/pages/SubmissionReviewPage.vue

fix(fe:FSADT1-1537): Fixed typo

---

frontend/src/assets/styles/global.scss
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/FormStaffConfirmationPage.vue
frontend/src/pages/FormStaffPage.vue
frontend/src/pages/FormStaffProcessingPage.vue
frontend/src/pages/LandingPage.vue
frontend/src/pages/LogoutPage.vue
frontend/tests/unittests/pages/FormStaffConfirmationPage.spec.ts
legacy/src/main/java/ca/bc/gov/app/entity/ForestClientLocationEntity.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchIndividualControllerIntegrationTest.java
legacy/src/test/java/ca/bc/gov/app/mappers/ForestClientContactMapperTest.java
legacy/src/test/java/ca/bc/gov/app/mappers/ForestClientMapperTest.java

feat(fe:FSADT1-1487): Client number screen - clickable client number

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded @cypress/code-coverage 3.13.4

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded @typescript-eslint/eslint-plugin 7.18.0

---

legacy/src/main/java/ca/bc/gov/app/configuration/ForestClientConfiguration.java
legacy/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java
legacy/src/main/resources/application.yml

Limited the query to search by recent record, using updated and created dates
---

chore(FSADT1-1553): changed no param full search 

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded @types/node 2.15.0

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded @typescript-eslint/parser 7.18.0

---

backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java

fix(be): CLIENT_SUSPEND - searching error

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade aws-amplify 6.6.6

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade @types/node 20.17.0

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade eslint-plugin-vue 9.29.1

---

frontend/src/pages/SubmissionReviewPage.vue

feat(fe:FSADT1-952): Make Client Number clickable

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade wiremock 3.9.2

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade vue 3.15.12

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded cypress 13.15.1

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade sass 1.80.4

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgrade vite 5.4.10

---

frontend/cypress/support/component.ts
frontend/src/components/forms/AutoCompleteInputComponent.vue
frontend/src/helpers/ForestClientUserSession.ts
frontend/src/pages/SearchPage.vue
frontend/src/pages/SubmissionReviewPage.vue
frontend/src/pages/staffform/ReviewWizardStep.vue
frontend/src/services/ForestClientService.ts

feat(fe:FSADT1-1565): Highlight text on Auto Complete options

---

frontend/cypress/e2e/pages/SearchPage.cy.ts
frontend/src/pages/SearchPage.vue
frontend/stub/mappings/client_search.json

Trims the search keywords in the request and in the displayed messages.
Fixes [FSADT1-1569](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1569)
---

fix(fe:FSADT1-1569): trim search keywords

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded vue-tsc 2.1.10

---

frontend/cypress/e2e/pages/SearchPage.cy.ts
frontend/src/pages/SearchPage.vue

Still trims the search keywords in the request and in the displayed messages, but keep duplicate spaces in the middle of it.
This is a follow-up from #1294.
Fixes [FSADT1-1569](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1569)
---

fix(fe:FSADT1-1569): do not remove duplicate spaces in the middle of the search terms

---

frontend/openshift.configmap.dev.yml
frontend/openshift.configmap.test.yml
frontend/package.json
frontend/src/components/MainHeaderComponent.vue
frontend/src/routes.ts

chore(fe): removed feature flag related to the search

---

.github/workflows/merge.yml
.github/workflows/pr-open.yml
legacy/openshift.deploy.yml
processor/openshift.deploy.yml

ci: deployment config deprecation for processor, legacy

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded cypress 13.15.2

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded @types/node 22.9.0

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded @cypress/code-coverage 3.13.6

---

processor/pom.xml

chore(be): Made sure both dependencies use the same version.

---

processor/pom.xml

chore(be): Upgraded netty 4.1.115

---

.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

ci: PR Results gate

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

ci: catch canceled jobs

---

.github/workflows/analysis.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml
processor/Dockerfile

ci(fix): catch canceled jobs

---

.github/workflows/pr-open.yml

Fixing scaling up and down the deployment of the legacy app
---

chore: fixing scale up and down

---

frontend/src/assets/styles/global.scss

Adds css class no-margin which was missed in #1358.
Also makes an adjustment on body-compact-01.
Fixes [FSADT1-1593](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1593)
---

fix(fe:FSADT1-1593): add missing css class

---

frontend/Dockerfile

Fixing security issue with npm install script
---

fix(sec): fixing possible security issue

---

.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml

Reducing workflow verbosity
---

chore: workflow verbosity reduction

---

frontend/src/pages/ClientDetailsPage.vue
frontend/stub/__files/response-clients-details-null.json
frontend/stub/mappings/client_details.json

Prevent from crashing when addresses is null.
Fixes [FSADT1-1593](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1593)
---

fix(fe:FSADT1-1593): prevent issue with addresses null

---

frontend/cypress/e2e/pages/ClientDetailsPage.cy.ts
frontend/src/assets/styles/global.scss
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/ClientDetailsPage.vue
frontend/src/pages/client-details/ContactView.vue
frontend/stub/__files/response-clients-details-G.json
frontend/stub/__files/response-clients-details-GD.json
frontend/stub/__files/response-clients-details-I.json
frontend/stub/__files/response-clients-details-IV.json
frontend/stub/__files/response-clients-details-S.json
frontend/stub/__files/response-clients-details-SE.json
frontend/tests/components/pages/client-details/ContactView.cy.ts

Adds the Contacts content (view mode) on the Client details page.
Fixes [FSADT1-1595](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1595)
---

feat(fe:FSADT1-1595): CLIENT_VIEWER Client Contacts Section - Front-End

---

frontend/cypress/e2e/pages/ClientDetailsPage.cy.ts
frontend/src/assets/styles/global.scss
frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/ClientDetailsPage.vue
frontend/src/pages/client-details/ContactView.vue
frontend/stub/__files/response-clients-details-G.json
frontend/stub/__files/response-clients-details-S.json
frontend/tests/components/pages/client-details/ContactView.cy.ts

Fixes two styles used for accordion's title on the following locations:
- Client View page;
- Submission Review page.
Also makes some adjustments on Contact view:
- Removes contactCode;
- Adds numeric index;
- Sorts by name.
Fixes [FSADT1-1682](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1682)
---
- [Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/workflows/merge.ym …

feat(fe:FSADT1-1682): CLIENT_VIEWER Client Location/Contact accordion title style

---

frontend/src/pages/ClientDetailsPage.vue

fix(fe): fix style on summary title

---

legacy/src/main/java/ca/bc/gov/app/repository/ClientDoingBusinessAsRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java

Fixing doing business as loading. Filled the list of possible doing business as values, as the frontend will find the appropriate one to show.
---

fix(FSADT1-1593): fixing doing business as loading

---

backend/src/main/java/ca/bc/gov/app/converters/ForestClientObfuscate.java

fix(FSADT1-1694): change obfuscation to BCSC value

---

.github/workflows/.tools-deploy.yml
.github/workflows/issue-gherkin.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
.github/workflows/reusable-tests-be.yml
.github/workflows/reusable-tests-fe.yml

chore(ci): actions moved to bcgov org

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded vue libraries

---

.github/workflows/merge.yml

chore(ci): remove JS handling from workflow conditionals

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientLegacyService.java

feat(be): Added missing status codes for Admin

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded sass

---

frontend/src/pages/bceidform/BusinessInformationWizardStep.vue

feat(fe:FSADT1-1695): Change email to link

---

processor/pom.xml

chore(processor): Fixed arbitrary code execution via JaninoEventEvaluator

---

backend/pom.xml
legacy/pom.xml

chore: Fixed arbitrary code execution via JaninoEventEvaluator

---

cypress/package-lock.json

chore(cypress): fixed Use of Insufficiently Random Values in undici

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientLegacyService.java
backend/src/test/java/ca/bc/gov/app/service/client/ClientLegacyServiceIntegrationTest.java

chore(be:FSADT1-1707): Updates in API that retrieves client statuses

---

frontend/src/pages/client-details/SummaryView.vue
frontend/tests/components/pages/client-details/SummaryView.cy.ts

This is a fix for https://github.com/bcgov/nr-forest-client/pull/1419 to prevent a CLIENT_EDITOR to edit the Client status when it's DECEASED.
Fixes [FSADT1-1598](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1598)
---

fix(fe): do not allow CLIENT_EDITOR to edit Client status when it's DECEASED

---

backend/src/main/java/ca/bc/gov/app/dto/legacy/ForestClientDetailsDto.java
backend/src/main/java/ca/bc/gov/app/dto/legacy/ForestClientLocationDetailsDto.java
backend/src/test/java/ca/bc/gov/app/service/client/ClientServiceIntegrationTest.java
legacy/src/main/java/ca/bc/gov/app/dto/ForestClientDetailsDto.java
legacy/src/main/java/ca/bc/gov/app/dto/ForestClientLocationDetailsDto.java
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientLocationRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-31-frontend.apps.silver.devops.gov.bc.ca/)

feat(be:FSADT1-1722): Adjust province and country information in Client Details API

---

.github/workflows/.tools-deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

chore(deps): update action-deployer-openshift to v4

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded bcgov and other dependencies

---

backend/openshift.deploy.yml

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-49-frontend.apps.silver.devops.gov.bc.ca/)

fix: reinstating backend route

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded cypress dependencies

---

frontend/src/components/forms/ComboBoxInputComponent.vue
frontend/src/components/grouping/StaffLocationGroupComponent.vue
frontend/src/pages/client-details/LocationView.vue
frontend/src/services/ForestClientService.ts
frontend/tests/components/pages/client-details/LocationView.cy.ts
frontend/tests/components/pages/staffform/LocationsWizardStep.cy.ts
frontend/tests/unittests/components/forms/ComboBoxInputComponent.spec.ts

Displays the country name in the input by picking finding the country by code.
And also prevents crashing when highlighting a matched search term.
Fixes [FSADT1-1603](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1603)
---

fix(fe: FSADT1-1603): display country name in the input

---

legacy/pom.xml
legacy/src/main/resources/application.yml

This will freeze for now the oracle driver, preventing issues with thumbprint on the certificate 
---

chore(deps): freezing oracle driver version

---

frontend/cypress/e2e/pages/ClientDetailsPage.cy.ts
frontend/src/App.vue

Fixing the test the fails in the workflow...
Fixes #1469 
---

test: wait loading the list before spying

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml
common/openshift.init.yml
legacy/openshift.deploy.yml

Simplify and tie the common deployer into TEST deployments.  PROD can be handled in a later PR.
---

chore(ci): common deployer ii

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/reusable-tests-fe.yml
backend/openshift.deploy.yml
common/openshift.init.yml

Troubleshooting.  Not ready for PROD yet.
---
---
Please create PRs in draft mode.  Mark …

chore(ci): common deployer iii

---

.github/workflows/merge.yml

chore(ci): common deployer for PROD

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

chore(ci): remaining deployment vars

---

.github/workflows/.deploy.yml
.github/workflows/.tools-deploy.yml
.github/workflows/pr-open.yml
common/openshift.init.yml
legacy/openshift.deploy.yml

fix: changing deployment params

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientSubmissionService.java
backend/src/main/resources/templates/approval.html
backend/src/main/resources/templates/registration.html
backend/src/main/resources/templates/rejection.html
legacydb/openshift.deploy.yml

fix(FSADT1-1734): Generate separate anchors for multiple email addresses

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded axios to 1.8.4

---

.github/workflows/.deploy.yml
.github/workflows/pr-open.yml
frontend/openshift.deploy.yml

ci: updating deployer

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java

feat(be:FSADT1-1703): Changed predictive query to use like instead

---

frontend/src/App.vue
frontend/src/components/MainHeaderComponent.vue

feat(fe:FSADT1-1576): Remove modal and use hyperlink instead

---

.github/workflows/.deploy.yml
.github/workflows/merge.yml
.github/workflows/pr-open.yml

chore(ci): configmap mangling

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java

feat(be:FSADT1-1755): Added more conditional fields to the predictive search query

---

backend/pom.xml

fix(be): Fixed code scanning issue with spring-security-crypto

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java

feat(be:FSADT1-1760): Included the similarity-based search if no matches are found using "like"

---

frontend/cypress/support/commands.ts
frontend/src/pages/SubmissionListPage.vue

Add a instruction message with a link to a page with information about applying to a client number.
Fixes [FSADT1-1742](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1742)
---

feat(fe:FSADT1-1742): As a staff, I want to know where the applicants applies for a client number

---

legacy/pom.xml
legacy/src/main/resources/application.yml
legacy/src/test/java/ca/bc/gov/app/util/PatchUtilsTest.java

chore(be): Upgraded ojdbc11 oracle driver and cleaned code

---

frontend/src/components/grouping/StaffLocationGroupComponent.vue
frontend/src/services/ForestClientService.ts
frontend/tests/unittests/services/ForestClientService.spec.ts

Makes sure to always use the index for names in the same format: padded with zeros to the left.
Fixes [FSADT1-1758](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1758)
---

fix(fe:FSADT1-1758): Edit Location - wrong duplicate name detection

---

backend/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
backend/src/main/java/ca/bc/gov/app/controller/client/ClientPatchController.java
backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientLegacyService.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientPatchService.java
legacy/src/main/java/ca/bc/gov/app/ApplicationConstants.java
legacy/src/main/java/ca/bc/gov/app/configuration/GlobalServiceConfiguration.java
legacy/src/main/java/ca/bc/gov/app/controller/ClientPatchController.java
legacy/src/main/java/ca/bc/gov/app/service/patch/ClientPatchOperation.java
legacy/src/main/java/ca/bc/gov/app/service/patch/ClientPatchService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationClientService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientPatchControllerIntegrationTest.java

- Added username/userId information to patch requests and logging.
- Migrated patch payload types from Object to JsonNode for improved JSON processing.
- Expanded authorization rules to permit admin access for patch endpoints.
---
---
Deployments, as required, will be available …

chore: small patch changes

---

frontend/package-lock.json
frontend/package.json

chore(be): upgraded cypress to 14.2.1

---

legacy/src/test/resources/db/migration/V12__client_location_trigger.sql

Just updating some scripts
---

chore: fixing location trigger

---

legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationContactRemoveService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientPatchControllerIntegrationTest.java

Added the remove option to contact
---

feat(FSADT1-1737): added remove contact patch service

---

legacy/src/main/java/ca/bc/gov/app/dto/ForestClientContactDetailsDto.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationContactAddService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientPatchControllerIntegrationTest.java

Added the add operation for contact
---

feat(FSADT1-1737): added add contact patch service and tests

---

backend/src/main/java/ca/bc/gov/app/security/ApiAuthorizationCustomizer.java

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-39-frontend.apps.silver.devops.gov.bc.ca/)

feat(be:FSADT1-1781-2-4): Adding suspend role to access the roles that editor has

---

frontend/src/pages/SubmissionListPage.vue

fix(fe:FSADT1-1782): Added suspend role in the FE as well

---

frontend/src/pages/SubmissionReviewPage.vue

fix(fe:FSADT1-1782): Added suspend role in the submission review page

---

legacy/src/test/resources/db/migration/V1.0.0__migration_01.txt

Adding instruction migration file
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-48-frontend.apps.silver.devops.gov.bc.ca/)

chore: adding migration readme

---

legacy/README.md
legacy/src/main/java/ca/bc/gov/app/controller/ClientSearchController.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java

fix(be): Adjusted shouldSearchEmpty integration test to expect empty result list and zero total count

---

frontend/src/assets/styles/global.scss
frontend/src/pages/ClientDetailsPage.vue

Shows the button to Add contact when there are no contacts yet.
Fixes [FSADT1-1803](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1803)
---
---
Any successful deployments (not always required) will be available …

fix(fe:FSADT1-1803): CLIENT_EDITOR - Missing Add Contact Button

---

.github/workflows/.automated-tests.yml
.github/workflows/.tools-cleanup.yml
.github/workflows/.tools-deploy.yml
.github/workflows/analysis.yml
.github/workflows/issue-gherkin.yml
.github/workflows/merge.yml
.github/workflows/pr-close.yml
.github/workflows/pr-open.yml
.github/workflows/pr-validate.yml
.github/workflows/reusable-tests-be.yml
.github/workflows/reusable-tests-fe.yml
.github/workflows/scheduled.yml

Intended to resolve a number of security alerts.
---

chore(ci): workflow permissions

---

frontend/src/dto/CommonTypesDto.ts
frontend/src/pages/client-details/SummaryView.vue
frontend/stub/__files/response-clients-details-C.json
frontend/stub/__files/response-clients-details-G+location.json
frontend/stub/__files/response-clients-details-G.json
frontend/stub/__files/response-clients-details-GD.json
frontend/stub/__files/response-clients-details-NL.json
frontend/stub/__files/response-clients-details-S.json
frontend/stub/__files/response-clients-details-SE.json
frontend/tests/components/pages/client-details/SummaryView.cy.ts

Updates the front-end code to match the update in the API ([FSADT1-1795](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1795)) so as to display only one value for Doing Business As.
Fixes [FSADT1-1728](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1728)
---

feat(fe:FSADT1-1728): Display only one Doing Business As (front-end)

---

legacy/src/main/java/ca/bc/gov/app/entity/ClientUpdateReasonEntity.java
legacy/src/main/java/ca/bc/gov/app/entity/LocationUpdateReasonEntity.java
legacy/src/main/java/ca/bc/gov/app/repository/LocationUpdateReasonRepository.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationAddressService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationLocationService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationStatusService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientPatchControllerIntegrationTest.java

Added the capability to update a location address. This will handle the reason code update for a location address update.
---

feat(FSADT1-1801|FSADT1-1802|FSADT1-1807): added location address update

---

backend/pom.xml
legacy/pom.xml
processor/pom.xml

chore: upgrade Spring Boot to 3.4.5 to fix CVE-2025-22235

---

frontend/src/pages/client-details/LocationView.vue
frontend/src/services/ForestClientService.ts
frontend/tests/unittests/services/ForestClientService.spec.ts
legacy/README.md
legacy/src/main/java/ca/bc/gov/app/repository/ForestClientLocationRepository.java
legacy/src/main/java/ca/bc/gov/app/service/ClientSearchService.java
legacy/src/main/java/ca/bc/gov/app/util/ReplacePatchUtils.java

The change involved fixing the issue with delivery address composition, ensuring that addresses are correctly formatted and complete. Context: This fix improves user experience when placing orders. Dependency changes include updates to the address validation library.
---

fix(FSADT1-1827): fixing delivery address sorting

---

.github/workflows/pr-validate.yml
backend/src/main/java/ca/bc/gov/app/service/client/ClientPatchService.java
backend/src/main/java/ca/bc/gov/app/service/client/validators/AcronymPatchValidator.java
backend/src/main/java/ca/bc/gov/app/service/client/validators/PatchValidator.java
backend/src/test/java/ca/bc/gov/app/service/client/ClientPatchServiceIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/service/client/validators/AcronymPatchValidatorIntegrationTest.java
legacy/src/main/java/ca/bc/gov/app/service/patch/ClientPatchService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationClientService.java

- Added acronym patch
- Added acronym validator
- Added patch validator classes
---

feat(FSADT1-1818): added acronym support and validation

---

legacy/src/main/java/ca/bc/gov/app/service/ClientService.java

fix(be:FSADT1-1775): Fixed Client History sorting after merging data

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientQueries.java
legacy/src/main/java/ca/bc/gov/app/service/ClientService.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java

fix(be:FSADT1-1775): Concatenated some fields in the history as per requested

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientQueries.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java

- Reverted concatenation for city and province
- Added format to phone numbers
- Fixed contact query
---

fix(be:FSADT1-1775): Changes to the History API

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientQueries.java

---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-39-frontend.apps.silver.devops.gov.bc.ca/)

fix(be:FSADT1-1775-5): Fixed bug with location status and made formatting fixes

---

frontend/cypress/e2e/pages/ClientDetailsPage.cy.ts
frontend/src/services/ForestClientService.ts
frontend/tests/unittests/services/ForestClientService.spec.ts

Updates the reason's field value to use the complete path to fields.
For example:
A reason value that used to have:
`field: "clientStatusCode"`
Will now have:
`field: "/client/clientStatusCode"`
Also updates the following reason's field for Individual clients:
- NAME: "/client/name" (virtual field for the group of fields related to client's full name)
- ID: "/client/id" (virtual field for the group of fields related to client's ID)
Note: when the clientName is changed on a non-Individual client, the field will be simply "/client/clientName", because in this case the value is not considered to be in a group of fields, like it is for Individuals (legalFirstName, legalMiddleName and clientName).
---
Any successful …

fix(fe): fix the reason's field value

---

backend/pom.xml
legacy/pom.xml
processor/pom.xml

chore(be): Fixed code security alert. CVE-2024-38820 ensured Locale-independent, lowercase conversion

---

.github/workflows/scheduled.yml

fix: schemaspy

---

frontend/cypress/e2e/pages/ClientDetailsPage.cy.ts
frontend/src/pages/client-details/HistoryView.vue

feat(fe:FSADT1-1875): History Tab - make details collapsed

---

backend/src/main/java/ca/bc/gov/app/controller/client/ClientPatchController.java
backend/src/main/java/ca/bc/gov/app/service/client/ClientPatchService.java
backend/src/main/java/ca/bc/gov/app/util/PatchUtils.java
backend/src/main/java/ca/bc/gov/app/validator/PatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/AcronymPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/AdminRolePatchValidator.java
backend/src/test/java/ca/bc/gov/app/service/client/validators/AcronymPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/AcronymPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/AdminRolePatchValidatorIntegrationTest.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationAddressService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationClientService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationContactAddService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationContactAssociationService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationContactEditService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationContactRemoveService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationLocationService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationNameService.java
legacy/src/main/java/ca/bc/gov/app/service/patch/PatchOperationStatusService.java
legacy/src/main/java/ca/bc/gov/app/util/PatchUtils.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientPatchControllerIntegrationTest.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchControllerIntegrationTest.java

This PR fixes [FSADT1-1871](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1871) by adding patch processing for client names and related fields. It also updates integration tests for patch operations, refactors utility methods for safe JSON Patch handling, and adjusts the ordering of patch operation services.
---
- [Merge Workflow](https://github.com/bcgov/nr-forest-client/actions/workf …

fix(FSADT1-1871): added patch processing for client name

---

legacy/src/main/java/ca/bc/gov/app/mappers/ForestClientMapper.java
processor/src/main/java/ca/bc/gov/app/service/legacy/LegacyAbstractPersistenceService.java
processor/src/test/java/ca/bc/gov/app/service/legacy/LegacyIndividualPersistenceServiceTest.java

fix(FSADT1-1879): changing wcbFirmNumber to save null as default

---

frontend/src/pages/client-details/SummaryView.vue
frontend/tests/components/pages/client-details/SummaryView.cy.ts

Removes the BC Registries standing read-only information from First Nation types.
Also fixes the displaying of the Registration number for the following types:
- First Nation Band - added the missing info;
- First Nation Group - removed the info displayed by mistake.
Fixes [FSADT1-1887](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1887)
---
- [Merge …

feat(fe:FSADT1-1887): Client Type - First Nation - No BC Registry Field

---

frontend/src/components/grouping/FuzzyMatchNotificationGroupingComponent.vue
frontend/src/pages/SubmissionReviewPage.vue

Fixes the hash value used on links, caused by #1631.
Fixes [FSADT1-1894](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1894)
---

fix(fe:FSADT1-1894): Links does not load location.

---

frontend/src/pages/client-details/RegistrationNumber.vue
frontend/stub/__files/response-clients-details-P+contact.json
frontend/stub/__files/response-clients-details-P+location.json
frontend/stub/__files/response-clients-details-P-contact.json
frontend/stub/__files/response-clients-details-PD.json
frontend/stub/__files/response-clients-details-PDAC.json
frontend/stub/__files/response-clients-details-PSPN.json
frontend/tests/components/pages/client-details/RegistrationNumber.cy.ts

Turns the Registration number fields required.
Fixes [FSADT1-1897](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1897), [FSADT1-1898](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1898)
---
---
Any successful deployments …

fix(fe:FSADT1-1897,FSADT1-1898): CLIENT_ADMIN - Mandatory fields

---

frontend/src/pages/ClientDetailsPage.vue
frontend/src/pages/client-details/SummaryView.vue
frontend/tests/components/pages/client-details/SummaryView.cy.ts

Displays the new client name instead of the old one in the success notification.
Fixes [FSADT1-1906](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1906)
---

fix(fe:FSADT1-1906): Outdated client name displayed in the notification

---

backend/pom.xml
processor/pom.xml

chore(be): Fixed code security alert. CVE-2025-49146 pgjdbc insecure authentication in channel binding
---

chore(be): Fixed code security alert CVE-2025-49146

---

frontend/cypress/e2e/pages/SubmissionReviewPage.cy.ts
frontend/src/pages/SubmissionReviewPage.vue

feat(fe:FSADT1-1907): Changed wording as per requested

---

frontend/stub/mappings/client_good_standing_indicator.json

chore(fe): added stub for good standing API

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded cypress to 14.4.1

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded types/node to 24.0.3

---

frontend/src/pages/client-details/SummaryView.vue

feat(fe:FSADT1-1715): Adjusted label as per requested

---

.github/workflows/pr-open.yml
backend/Dockerfile
backend/pom.xml
legacy/Dockerfile
legacy/pom.xml

ci: updating build args to reduce build time

---

frontend/package-lock.json
frontend/package.json

chore(fe): upgraded axios to 1.10.0

---

frontend/src/helpers/validators/StaffFormValidations.ts
frontend/src/pages/client-details/SummaryView.vue
frontend/src/pages/staffform/BcRegisteredClientInformationWizardStep.vue

Adds helper text to Client name.
Also adds ID number very basic validation.
And removes the mask from the Acronym input.
---
Any successful deployments (not always required) will be available [here](https://nr-forest-client-40-frontend.apps.silver.devops.gov.bc.ca/)

feat(fe): Client name helper text

---

frontend/src/helpers/validators/GlobalValidators.ts

chore(fe): Fixed code scanning alert "Exceptions should not be ignored"

---

backend/pom.xml
legacy/pom.xml
processor/pom.xml

chore: Fixed vulnerability CVE-2025-22227

---

cypress/cypress/e2e/staffCreate.feature
cypress/cypress/e2e/upt_1257.feature
frontend/cypress/e2e/pages/FormStaffPage.cy.ts
frontend/cypress/e2e/pages/FormStaffPageSubmission.cy.ts
frontend/cypress/fixtures/testdata/contactBaseData.json
frontend/src/dto/ApplyClientNumberDto.ts
frontend/src/pages/FormBCSCPage.vue
frontend/src/pages/FormBCeIDPage.vue
frontend/src/pages/bceidform/BusinessInformationWizardStep.vue
frontend/src/pages/bceidform/ContactWizardStep.vue
frontend/src/pages/staffform/ContactsWizardStep.vue

feat(fe:FSADT1-1959): Location – Name default is ‘Mailing address

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientPatchService.java
backend/src/main/java/ca/bc/gov/app/validator/PatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/AcronymPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/AdminRolePatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/BirthdatePatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/RegistrationNumberPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/RelatedClientsLocationPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/RelatedClientsPercentageOwnedPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/RelatedClientsRelatedClientLocationPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/RelatedClientsRelatedClientPatchValidator.java
backend/src/main/java/ca/bc/gov/app/validator/patch/RelatedClientsRelationshipTypePatchValidator.java
backend/src/test/java/ca/bc/gov/app/validator/patch/AcronymPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/BirthdatePatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/RegistrationNumberPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/RelatedClientsLocationPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/RelatedClientsPercentageOwnedPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/RelatedClientsRelatedClientLocationPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/RelatedClientsRelatedClientPatchValidatorIntegrationTest.java
backend/src/test/java/ca/bc/gov/app/validator/patch/RelatedClientsRelationshipTypePatchValidatorIntegrationTest.java
legacy/src/main/java/ca/bc/gov/app/service/ClientContactService.java

feat(fe:FSADT1-1965): Related client validations

---

frontend/src/pages/client-details/LocationRelationshipsView.vue
frontend/tests/components/pages/client-details/LocationRelationshipsView.cy.ts

Links to Google Maps using the address properly encoded.
Fixes [FSADT1-1952](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT1-1952)
---

feat(fe:FSADT1-1952): Link to a map application

---

backend/src/main/java/ca/bc/gov/app/service/client/ClientLegacyService.java
backend/src/test/java/ca/bc/gov/app/controller/client/ClientControllerIntegrationTest.java

fix(FSADT1-1981): fixed related client on client details

---

frontend/src/helpers/DataConverters.ts

feat(fe:FSADT1-1994): Added ULC legal type

---

legacy/src/main/java/ca/bc/gov/app/repository/ForestClientQueries.java
legacy/src/test/java/ca/bc/gov/app/controller/ClientSearchRelatedClientIntegrationTest.java

fix(be:FSADT1-2006): Fixed issue in search query
